import { Question } from './types';

// Batch 6 — hand-crafted exam-style questions. Every answer has been worked
// through and checked by hand. 5 questions per topic across all 10 topics.
export const batch6: Question[] = [
  // ── Logarithmic Functions & Indices ──
  {
    id: 'b6-1',
    topic: 'logarithmic-functions-and-indices',
    subtopic: 'Solving exponential equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $3^{2x-1} = 81$.',
    markScheme: '$81 = 3^4$ ✓\n$2x - 1 = 4$ ✓\n$x = \\dfrac{5}{2}$ ✓',
    workedSolution: 'Write both sides with base 3:\n$$3^{2x-1} = 81 = 3^4$$\nEquate the indices:\n$$2x - 1 = 4 \\implies 2x = 5 \\implies x = \\frac{5}{2}$$',
  },
  {
    id: 'b6-2',
    topic: 'logarithmic-functions-and-indices',
    subtopic: 'Logarithmic equations',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Given that $\\log_2 x = 5$, find the value of $x$.',
    markScheme: '$x = 2^5$ ✓\n$x = 32$ ✓',
    workedSolution: 'By the definition of a logarithm, $\\log_2 x = 5$ means:\n$$x = 2^5 = 32$$',
  },
  {
    id: 'b6-3',
    topic: 'logarithmic-functions-and-indices',
    subtopic: 'Laws of indices',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Simplify $\\dfrac{(2a^2 b)^3}{4ab^2}$.',
    markScheme: '$(2a^2 b)^3 = 8a^6 b^3$ ✓\n$\\dfrac{8a^6 b^3}{4ab^2} = 2a^5 b$ ✓✓',
    workedSolution: 'Cube the numerator:\n$$(2a^2 b)^3 = 2^3 a^{6} b^{3} = 8a^6 b^3$$\nNow divide:\n$$\\frac{8a^6 b^3}{4ab^2} = 2a^{6-1} b^{3-2} = 2a^5 b$$',
  },
  {
    id: 'b6-4',
    topic: 'logarithmic-functions-and-indices',
    subtopic: 'Solving exponential equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $2^x = 7$, giving your answer to 3 significant figures.',
    markScheme: 'Take logs: $x \\log 2 = \\log 7$ ✓\n$x = \\dfrac{\\log 7}{\\log 2}$ ✓\n$x = 2.81$ (3 s.f.) ✓',
    workedSolution: 'Take logarithms of both sides:\n$$\\log(2^x) = \\log 7 \\implies x \\log 2 = \\log 7$$\n$$x = \\frac{\\log 7}{\\log 2} = 2.807\\ldots = 2.81 \\text{ (3 s.f.)}$$',
  },
  {
    id: 'b6-5',
    topic: 'logarithmic-functions-and-indices',
    subtopic: 'Logarithmic equations',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 4,
    body: 'Solve $\\log_2 x + \\log_2 (x - 2) = 3$.',
    markScheme: '$\\log_2 (x(x-2)) = 3$ ✓\n$x^2 - 2x = 8$ ✓\n$(x-4)(x+2) = 0$ ✓\n$x = 4$ (reject $x = -2$) ✓',
    workedSolution: 'Combine the logs using the addition law:\n$$\\log_2 (x(x-2)) = 3 \\implies x(x-2) = 2^3 = 8$$\n$$x^2 - 2x - 8 = 0 \\implies (x-4)(x+2) = 0$$\nSo $x = 4$ or $x = -2$. Reject $x = -2$ since $\\log_2(-2)$ is undefined.\n$$x = 4$$',
  },

  // ── The Quadratic Function ──
  {
    id: 'b6-6',
    topic: 'the-quadratic-function',
    subtopic: 'Completing the square',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Express $x^2 - 8x + 3$ in the form $(x + a)^2 + b$.',
    markScheme: '$(x - 4)^2 - 16 + 3$ ✓\n$(x - 4)^2 - 13$ ✓',
    workedSolution: 'Halve the coefficient of $x$ and complete the square:\n$$x^2 - 8x + 3 = (x-4)^2 - 4^2 + 3 = (x-4)^2 - 13$$',
  },
  {
    id: 'b6-7',
    topic: 'the-quadratic-function',
    subtopic: 'Discriminant',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the values of $k$ for which $x^2 + kx + 4 = 0$ has equal roots.',
    markScheme: 'Equal roots $\\Rightarrow \\Delta = 0$ ✓\n$k^2 - 16 = 0$ ✓\n$k = \\pm 4$ ✓',
    workedSolution: 'For equal roots the discriminant is zero:\n$$\\Delta = b^2 - 4ac = k^2 - 4(1)(4) = 0$$\n$$k^2 = 16 \\implies k = \\pm 4$$',
  },
  {
    id: 'b6-8',
    topic: 'the-quadratic-function',
    subtopic: 'Quadratic formula',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $2x^2 - 5x - 3 = 0$.',
    markScheme: '$(2x + 1)(x - 3) = 0$ ✓✓\n$x = -\\dfrac{1}{2}$ or $x = 3$ ✓',
    workedSolution: 'Factorise:\n$$2x^2 - 5x - 3 = (2x + 1)(x - 3) = 0$$\nSo $2x + 1 = 0$ or $x - 3 = 0$, giving:\n$$x = -\\frac{1}{2} \\quad \\text{or} \\quad x = 3$$',
  },
  {
    id: 'b6-9',
    topic: 'the-quadratic-function',
    subtopic: 'Quadratic graphs',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the coordinates of the minimum point of the curve $y = x^2 - 6x + 11$.',
    markScheme: '$(x-3)^2 - 9 + 11 = (x-3)^2 + 2$ ✓✓\nMinimum at $(3, 2)$ ✓',
    workedSolution: 'Complete the square:\n$$y = x^2 - 6x + 11 = (x-3)^2 - 9 + 11 = (x-3)^2 + 2$$\nThe minimum value is $2$, occurring when $x = 3$. Minimum point: $(3, 2)$.',
  },
  {
    id: 'b6-10',
    topic: 'the-quadratic-function',
    subtopic: 'Simultaneous equations',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'Solve the simultaneous equations\n$$y = x^2 - 3x + 2 \\qquad y = 2x - 2$$',
    markScheme: '$x^2 - 3x + 2 = 2x - 2$ ✓\n$x^2 - 5x + 4 = 0 \\Rightarrow (x-1)(x-4) = 0$ ✓\n$x = 1, y = 0$ ✓\n$x = 4, y = 6$ ✓',
    workedSolution: 'Set the expressions for $y$ equal:\n$$x^2 - 3x + 2 = 2x - 2$$\n$$x^2 - 5x + 4 = 0 \\implies (x-1)(x-4) = 0$$\nSo $x = 1$ or $x = 4$. Substitute into $y = 2x - 2$:\n$$x = 1 \\Rightarrow y = 0, \\qquad x = 4 \\Rightarrow y = 6$$\nSolutions: $(1, 0)$ and $(4, 6)$.',
  },

  // ── Identities & Inequalities ──
  {
    id: 'b6-11',
    topic: 'identities-and-inequalities',
    subtopic: 'Remainder theorem',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the remainder when $f(x) = x^3 - 2x^2 + 3x - 5$ is divided by $(x - 2)$.',
    markScheme: 'Remainder $= f(2)$ ✓\n$f(2) = 8 - 8 + 6 - 5 = 1$ ✓',
    workedSolution: 'By the remainder theorem, the remainder is $f(2)$:\n$$f(2) = (2)^3 - 2(2)^2 + 3(2) - 5 = 8 - 8 + 6 - 5 = 1$$',
  },
  {
    id: 'b6-12',
    topic: 'identities-and-inequalities',
    subtopic: 'Factor theorem',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 2,
    body: 'Show that $(x + 1)$ is a factor of $f(x) = 2x^3 + x^2 - 2x - 1$.',
    markScheme: 'Evaluate $f(-1)$ ✓\n$f(-1) = -2 + 1 + 2 - 1 = 0$, so $(x+1)$ is a factor ✓',
    workedSolution: 'By the factor theorem, $(x+1)$ is a factor if $f(-1) = 0$:\n$$f(-1) = 2(-1)^3 + (-1)^2 - 2(-1) - 1 = -2 + 1 + 2 - 1 = 0$$\nSince $f(-1) = 0$, $(x+1)$ is a factor of $f(x)$.',
  },
  {
    id: 'b6-13',
    topic: 'identities-and-inequalities',
    subtopic: 'Linear inequalities',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Solve the inequality $3x - 7 < x + 5$.',
    markScheme: '$2x < 12$ ✓\n$x < 6$ ✓',
    workedSolution: 'Collect terms:\n$$3x - 7 < x + 5 \\implies 2x < 12 \\implies x < 6$$',
  },
  {
    id: 'b6-14',
    topic: 'identities-and-inequalities',
    subtopic: 'Quadratic inequalities',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $x^2 - x - 12 > 0$.',
    markScheme: '$(x - 4)(x + 3) > 0$ ✓\nCritical values $x = 4, -3$ ✓\n$x < -3$ or $x > 4$ ✓',
    workedSolution: 'Factorise:\n$$x^2 - x - 12 = (x - 4)(x + 3) > 0$$\nThe critical values are $x = -3$ and $x = 4$. Since this is a positive (U-shaped) parabola, it is above the $x$-axis outside the roots:\n$$x < -3 \\quad \\text{or} \\quad x > 4$$',
  },
  {
    id: 'b6-15',
    topic: 'identities-and-inequalities',
    subtopic: 'Polynomial division',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'Given that $(x - 3)$ is a factor of $f(x) = x^3 - 4x^2 + x + 6$, factorise $f(x)$ completely.',
    markScheme: '$f(3) = 27 - 36 + 3 + 6 = 0$ confirms factor ✓\nDivide: $f(x) = (x-3)(x^2 - x - 2)$ ✓\n$x^2 - x - 2 = (x-2)(x+1)$ ✓\n$f(x) = (x-3)(x-2)(x+1)$ ✓',
    workedSolution: 'Check the factor: $f(3) = 27 - 36 + 3 + 6 = 0$ ✓\n\nDividing $f(x)$ by $(x - 3)$ gives the quotient $x^2 - x - 2$:\n$$f(x) = (x - 3)(x^2 - x - 2)$$\nFactorise the quadratic:\n$$x^2 - x - 2 = (x - 2)(x + 1)$$\nTherefore:\n$$f(x) = (x - 3)(x - 2)(x + 1)$$',
  },

  // ── Graphs ──
  {
    id: 'b6-16',
    topic: 'graphs',
    subtopic: 'Graph transformations',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'The curve $y = f(x)$ passes through the point $(2, 5)$. State the coordinates of the corresponding point on the curve $y = f(x) + 3$.',
    markScheme: 'Translation 3 up: $y$-coordinate increases by 3 ✓\n$(2, 8)$ ✓',
    workedSolution: 'The transformation $y = f(x) + 3$ is a translation of 3 units in the positive $y$-direction. The $x$-coordinate is unchanged:\n$$(2, 5) \\to (2, 8)$$',
  },
  {
    id: 'b6-17',
    topic: 'graphs',
    subtopic: 'Graph transformations',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Describe fully the single transformation that maps the graph of $y = x^2$ onto the graph of $y = (x - 4)^2$.',
    markScheme: 'Translation ✓\n4 units in the positive $x$-direction (right) ✓',
    workedSolution: 'Replacing $x$ with $(x - 4)$ shifts the graph horizontally. The transformation is a translation of $\\begin{pmatrix} 4 \\\\ 0 \\end{pmatrix}$, i.e. 4 units in the positive $x$-direction.',
  },
  {
    id: 'b6-18',
    topic: 'graphs',
    subtopic: 'Modulus function',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $|2x - 1| = 5$.',
    markScheme: '$2x - 1 = 5 \\Rightarrow x = 3$ ✓\n$2x - 1 = -5 \\Rightarrow x = -2$ ✓\n$x = 3$ or $x = -2$ ✓',
    workedSolution: 'The modulus equation gives two cases:\n$$2x - 1 = 5 \\implies 2x = 6 \\implies x = 3$$\n$$2x - 1 = -5 \\implies 2x = -4 \\implies x = -2$$\nSo $x = 3$ or $x = -2$.',
  },
  {
    id: 'b6-19',
    topic: 'graphs',
    subtopic: 'Sketching curves',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'The point $(3, -2)$ lies on the curve $y = f(x)$. Find the coordinates of the corresponding point on the curve $y = f(x - 1) - 4$.',
    markScheme: '$f(x-1)$: shift right 1 $\\Rightarrow (4, -2)$ ✓\n$-4$: shift down 4 $\\Rightarrow (4, -6)$ ✓✓',
    workedSolution: 'Apply the transformations in turn:\n- $y = f(x - 1)$ translates 1 unit right: $(3, -2) \\to (4, -2)$\n- $-4$ translates 4 units down: $(4, -2) \\to (4, -6)$\n\nThe corresponding point is $(4, -6)$.',
  },
  {
    id: 'b6-20',
    topic: 'graphs',
    subtopic: 'Graph transformations',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'The curve $y = f(x)$ has a vertex at $(-1, 4)$. State the coordinates of the vertex of the curve $y = -f(x)$.',
    markScheme: 'Reflection in the $x$-axis ✓\n$(-1, -4)$ ✓',
    workedSolution: 'The transformation $y = -f(x)$ reflects the curve in the $x$-axis, negating each $y$-coordinate:\n$$(-1, 4) \\to (-1, -4)$$',
  },

  // ── Series ──
  {
    id: 'b6-21',
    topic: 'series',
    subtopic: 'Arithmetic sequences',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'An arithmetic sequence has first term $7$ and common difference $4$. Find the 20th term.',
    markScheme: '$u_{20} = 7 + 19(4)$ ✓\n$= 83$ ✓',
    workedSolution: 'Using $u_n = a + (n-1)d$ with $a = 7$, $d = 4$, $n = 20$:\n$$u_{20} = 7 + (20 - 1)(4) = 7 + 76 = 83$$',
  },
  {
    id: 'b6-22',
    topic: 'series',
    subtopic: 'Arithmetic series',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the sum of the first 50 terms of the arithmetic series $3 + 7 + 11 + \\ldots$',
    markScheme: '$a = 3, d = 4$ ✓\n$S_{50} = \\dfrac{50}{2}(2(3) + 49(4))$ ✓\n$= 25(202) = 5050$ ✓',
    workedSolution: 'Here $a = 3$ and $d = 4$. Using $S_n = \\dfrac{n}{2}(2a + (n-1)d)$:\n$$S_{50} = \\frac{50}{2}\\big(2(3) + 49(4)\\big) = 25(6 + 196) = 25 \\times 202 = 5050$$',
  },
  {
    id: 'b6-23',
    topic: 'series',
    subtopic: 'Geometric sequences',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'A geometric sequence has first term $5$ and common ratio $3$. Find the 6th term.',
    markScheme: '$u_6 = 5 \\times 3^5$ ✓\n$= 1215$ ✓',
    workedSolution: 'Using $u_n = ar^{n-1}$ with $a = 5$, $r = 3$, $n = 6$:\n$$u_6 = 5 \\times 3^{5} = 5 \\times 243 = 1215$$',
  },
  {
    id: 'b6-24',
    topic: 'series',
    subtopic: 'Sum to infinity',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'A geometric series has first term $12$ and common ratio $\\dfrac{1}{3}$. Find its sum to infinity.',
    markScheme: '$|r| < 1$ so $S_\\infty$ exists ✓\n$S_\\infty = \\dfrac{12}{1 - \\frac{1}{3}}$ ✓\n$= 18$ ✓',
    workedSolution: 'Since $|r| = \\frac{1}{3} < 1$, the sum to infinity exists:\n$$S_\\infty = \\frac{a}{1 - r} = \\frac{12}{1 - \\frac{1}{3}} = \\frac{12}{\\frac{2}{3}} = 18$$',
  },
  {
    id: 'b6-25',
    topic: 'series',
    subtopic: 'Arithmetic sequences',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'The 3rd term of an arithmetic sequence is $17$ and the 7th term is $33$. Find the first term $a$ and the common difference $d$.',
    markScheme: '$a + 2d = 17$ and $a + 6d = 33$ ✓\nSubtract: $4d = 16 \\Rightarrow d = 4$ ✓\n$a = 17 - 8 = 9$ ✓✓',
    workedSolution: 'Write equations using $u_n = a + (n-1)d$:\n$$a + 2d = 17 \\quad (1)$$\n$$a + 6d = 33 \\quad (2)$$\nSubtract (1) from (2): $4d = 16$, so $d = 4$. Substitute into (1):\n$$a + 8 = 17 \\implies a = 9$$',
  },

  // ── The Binomial Series ──
  {
    id: 'b6-26',
    topic: 'the-binomial-series',
    subtopic: 'Binomial expansion (positive integer)',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the first three terms, in ascending powers of $x$, of the expansion of $(1 + 2x)^5$.',
    markScheme: '$\\binom{5}{0} + \\binom{5}{1}(2x) + \\binom{5}{2}(2x)^2$ ✓\n$= 1 + 10x + 40x^2$ ✓✓',
    workedSolution: 'Using the binomial theorem:\n$$(1 + 2x)^5 = 1 + \\binom{5}{1}(2x) + \\binom{5}{2}(2x)^2 + \\ldots$$\n$$= 1 + 5(2x) + 10(4x^2) + \\ldots = 1 + 10x + 40x^2 + \\ldots$$',
  },
  {
    id: 'b6-27',
    topic: 'the-binomial-series',
    subtopic: 'Binomial coefficients',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the coefficient of $x^3$ in the expansion of $(1 + x)^7$.',
    markScheme: 'Coefficient $= \\binom{7}{3}$ ✓\n$= 35$ ✓',
    workedSolution: 'The coefficient of $x^3$ in $(1+x)^7$ is $\\binom{7}{3}$:\n$$\\binom{7}{3} = \\frac{7!}{3!\\,4!} = \\frac{7 \\times 6 \\times 5}{3 \\times 2 \\times 1} = 35$$',
  },
  {
    id: 'b6-28',
    topic: 'the-binomial-series',
    subtopic: 'Binomial coefficients',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Evaluate $\\dbinom{8}{3}$.',
    markScheme: '$\\dfrac{8 \\times 7 \\times 6}{3!}$ ✓\n$= 56$ ✓',
    workedSolution: '$$\\binom{8}{3} = \\frac{8!}{3!\\,5!} = \\frac{8 \\times 7 \\times 6}{3 \\times 2 \\times 1} = \\frac{336}{6} = 56$$',
  },
  {
    id: 'b6-29',
    topic: 'the-binomial-series',
    subtopic: 'Binomial expansion (positive integer)',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the first three terms, in ascending powers of $x$, of the expansion of $(2 + x)^6$.',
    markScheme: '$2^6 + \\binom{6}{1}2^5 x + \\binom{6}{2}2^4 x^2$ ✓\n$= 64 + 192x + 240x^2$ ✓✓',
    workedSolution: 'Using the binomial theorem:\n$$(2 + x)^6 = 2^6 + \\binom{6}{1}2^5 x + \\binom{6}{2}2^4 x^2 + \\ldots$$\n$$= 64 + 6(32)x + 15(16)x^2 + \\ldots = 64 + 192x + 240x^2 + \\ldots$$',
  },
  {
    id: 'b6-30',
    topic: 'the-binomial-series',
    subtopic: 'Binomial coefficients',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 3,
    body: 'Find the coefficient of $x^2$ in the expansion of $(3 - 2x)^4$.',
    markScheme: 'Term $= \\binom{4}{2}(3)^2(-2x)^2$ ✓\n$= 6 \\times 9 \\times 4 x^2$ ✓\nCoefficient $= 216$ ✓',
    workedSolution: 'The $x^2$ term comes from $\\binom{4}{2}(3)^{2}(-2x)^{2}$:\n$$\\binom{4}{2}(3)^2(-2x)^2 = 6 \\times 9 \\times 4x^2 = 216x^2$$\nThe coefficient is $216$.',
  },

  // ── Scalar & Vector Quantities ──
  {
    id: 'b6-31',
    topic: 'scalar-and-vector-quantities',
    subtopic: 'Magnitude and direction',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the magnitude of the vector $\\begin{pmatrix} 8 \\\\ 15 \\end{pmatrix}$.',
    markScheme: '$\\sqrt{8^2 + 15^2}$ ✓\n$= \\sqrt{289} = 17$ ✓',
    workedSolution: 'The magnitude is:\n$$\\left| \\begin{pmatrix} 8 \\\\ 15 \\end{pmatrix} \\right| = \\sqrt{8^2 + 15^2} = \\sqrt{64 + 225} = \\sqrt{289} = 17$$',
  },
  {
    id: 'b6-32',
    topic: 'scalar-and-vector-quantities',
    subtopic: 'Vector addition',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Given $\\mathbf{a} = \\begin{pmatrix} 3 \\\\ 1 \\end{pmatrix}$ and $\\mathbf{b} = \\begin{pmatrix} -1 \\\\ 4 \\end{pmatrix}$, find $\\mathbf{a} + 2\\mathbf{b}$.',
    markScheme: '$2\\mathbf{b} = \\begin{pmatrix} -2 \\\\ 8 \\end{pmatrix}$ ✓\n$\\mathbf{a} + 2\\mathbf{b} = \\begin{pmatrix} 1 \\\\ 9 \\end{pmatrix}$ ✓',
    workedSolution: 'First find $2\\mathbf{b} = \\begin{pmatrix} -2 \\\\ 8 \\end{pmatrix}$, then add:\n$$\\mathbf{a} + 2\\mathbf{b} = \\begin{pmatrix} 3 \\\\ 1 \\end{pmatrix} + \\begin{pmatrix} -2 \\\\ 8 \\end{pmatrix} = \\begin{pmatrix} 1 \\\\ 9 \\end{pmatrix}$$',
  },
  {
    id: 'b6-33',
    topic: 'scalar-and-vector-quantities',
    subtopic: 'Position vectors',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 3,
    body: 'Points $A$ and $B$ have position vectors $\\mathbf{a} = \\begin{pmatrix} 2 \\\\ 3 \\end{pmatrix}$ and $\\mathbf{b} = \\begin{pmatrix} 6 \\\\ 6 \\end{pmatrix}$. Find $\\overrightarrow{AB}$ and its magnitude.',
    markScheme: '$\\overrightarrow{AB} = \\mathbf{b} - \\mathbf{a} = \\begin{pmatrix} 4 \\\\ 3 \\end{pmatrix}$ ✓✓\n$|\\overrightarrow{AB}| = \\sqrt{16 + 9} = 5$ ✓',
    workedSolution: '$$\\overrightarrow{AB} = \\mathbf{b} - \\mathbf{a} = \\begin{pmatrix} 6 \\\\ 6 \\end{pmatrix} - \\begin{pmatrix} 2 \\\\ 3 \\end{pmatrix} = \\begin{pmatrix} 4 \\\\ 3 \\end{pmatrix}$$\n$$|\\overrightarrow{AB}| = \\sqrt{4^2 + 3^2} = \\sqrt{25} = 5$$',
  },
  {
    id: 'b6-34',
    topic: 'scalar-and-vector-quantities',
    subtopic: 'Magnitude and direction',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the unit vector in the direction of $\\begin{pmatrix} 6 \\\\ 8 \\end{pmatrix}$.',
    markScheme: 'Magnitude $= \\sqrt{36 + 64} = 10$ ✓\nUnit vector $= \\dfrac{1}{10}\\begin{pmatrix} 6 \\\\ 8 \\end{pmatrix}$ ✓\n$= \\begin{pmatrix} 3/5 \\\\ 4/5 \\end{pmatrix}$ ✓',
    workedSolution: 'The magnitude is $\\sqrt{6^2 + 8^2} = \\sqrt{100} = 10$. Divide the vector by its magnitude:\n$$\\hat{\\mathbf{v}} = \\frac{1}{10}\\begin{pmatrix} 6 \\\\ 8 \\end{pmatrix} = \\begin{pmatrix} \\frac{3}{5} \\\\ \\frac{4}{5} \\end{pmatrix}$$',
  },
  {
    id: 'b6-35',
    topic: 'scalar-and-vector-quantities',
    subtopic: 'Geometric proofs with vectors',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 3,
    body: 'The vectors $\\begin{pmatrix} k \\\\ 3 \\end{pmatrix}$ and $\\begin{pmatrix} 4 \\\\ 6 \\end{pmatrix}$ are parallel. Find the value of $k$.',
    markScheme: 'Parallel $\\Rightarrow$ one is a scalar multiple of the other ✓\n$\\dfrac{k}{4} = \\dfrac{3}{6}$ ✓\n$k = 2$ ✓',
    workedSolution: 'Parallel vectors are scalar multiples, so the components are in the same ratio:\n$$\\frac{k}{4} = \\frac{3}{6} = \\frac{1}{2}$$\n$$k = \\frac{1}{2} \\times 4 = 2$$',
  },

  // ── Rectangular Cartesian Coordinates ──
  {
    id: 'b6-36',
    topic: 'rectangular-cartesian-coordinates',
    subtopic: 'Distance between points',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the distance between the points $A(1, 2)$ and $B(4, 6)$.',
    markScheme: '$\\sqrt{(4-1)^2 + (6-2)^2}$ ✓\n$= \\sqrt{25} = 5$ ✓',
    workedSolution: 'Using the distance formula:\n$$d = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5$$',
  },
  {
    id: 'b6-37',
    topic: 'rectangular-cartesian-coordinates',
    subtopic: 'Midpoints',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the midpoint of the line segment joining $A(-2, 5)$ and $B(6, 1)$.',
    markScheme: '$\\left(\\dfrac{-2+6}{2}, \\dfrac{5+1}{2}\\right)$ ✓\n$= (2, 3)$ ✓',
    workedSolution: 'Using the midpoint formula:\n$$M = \\left(\\frac{-2 + 6}{2}, \\frac{5 + 1}{2}\\right) = (2, 3)$$',
  },
  {
    id: 'b6-38',
    topic: 'rectangular-cartesian-coordinates',
    subtopic: 'Equation of a line',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the equation of the straight line through the point $(1, 2)$ with gradient $3$. Give your answer in the form $y = mx + c$.',
    markScheme: '$y - 2 = 3(x - 1)$ ✓\n$y = 3x - 3 + 2$ ✓\n$y = 3x - 1$ ✓',
    workedSolution: 'Use $y - y_1 = m(x - x_1)$ with $m = 3$ and $(x_1, y_1) = (1, 2)$:\n$$y - 2 = 3(x - 1) = 3x - 3$$\n$$y = 3x - 1$$',
  },
  {
    id: 'b6-39',
    topic: 'rectangular-cartesian-coordinates',
    subtopic: 'Perpendicular and parallel lines',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'A line $l_1$ has equation $y = 3x - 2$. Find the equation of the line $l_2$ that is perpendicular to $l_1$ and passes through the point $(3, 1)$. Give your answer in the form $ax + by = c$.',
    markScheme: 'Gradient of $l_1$ is $3$, so gradient of $l_2$ is $-\\dfrac{1}{3}$ ✓\n$y - 1 = -\\dfrac{1}{3}(x - 3)$ ✓\n$3y - 3 = -(x - 3)$ ✓\n$x + 3y = 6$ ✓',
    workedSolution: 'The gradient of $l_1$ is $3$, so the perpendicular gradient is $-\\dfrac{1}{3}$.\n$$y - 1 = -\\frac{1}{3}(x - 3)$$\nMultiply through by 3:\n$$3y - 3 = -(x - 3) = -x + 3$$\n$$x + 3y = 6$$',
  },
  {
    id: 'b6-40',
    topic: 'rectangular-cartesian-coordinates',
    subtopic: 'Circle equations',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'Find the centre and radius of the circle with equation $x^2 + y^2 - 6x + 4y - 12 = 0$.',
    markScheme: '$(x-3)^2 - 9 + (y+2)^2 - 4 - 12 = 0$ ✓✓\n$(x-3)^2 + (y+2)^2 = 25$ ✓\nCentre $(3, -2)$, radius $5$ ✓',
    workedSolution: 'Complete the square in $x$ and $y$:\n$$(x^2 - 6x) + (y^2 + 4y) - 12 = 0$$\n$$(x-3)^2 - 9 + (y+2)^2 - 4 - 12 = 0$$\n$$(x-3)^2 + (y+2)^2 = 25$$\nCentre $(3, -2)$ and radius $\\sqrt{25} = 5$.',
  },

  // ── Calculus ──
  {
    id: 'b6-41',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Differentiate $y = 4x^3 - 2x^2 + 7x - 1$ with respect to $x$.',
    markScheme: '$\\dfrac{dy}{dx} = 12x^2 - 4x + 7$ ✓✓',
    workedSolution: 'Differentiate term by term using $\\dfrac{d}{dx}(x^n) = nx^{n-1}$:\n$$\\frac{dy}{dx} = 12x^2 - 4x + 7$$',
  },
  {
    id: 'b6-42',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find $\\displaystyle\\int (6x^2 - 4x + 3)\\,dx$.',
    markScheme: '$\\dfrac{6x^3}{3} - \\dfrac{4x^2}{2} + 3x + c$ ✓✓\n$= 2x^3 - 2x^2 + 3x + c$ ✓',
    workedSolution: 'Integrate term by term, raising each power by 1:\n$$\\int (6x^2 - 4x + 3)\\,dx = 2x^3 - 2x^2 + 3x + c$$\nRemember the constant of integration $+c$.',
  },
  {
    id: 'b6-43',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Evaluate $\\displaystyle\\int_1^3 (2x + 1)\\,dx$.',
    markScheme: '$[x^2 + x]_1^3$ ✓\n$= (9 + 3) - (1 + 1)$ ✓\n$= 10$ ✓',
    workedSolution: 'Integrate then substitute the limits:\n$$\\int_1^3 (2x + 1)\\,dx = \\big[x^2 + x\\big]_1^3 = (9 + 3) - (1 + 1) = 12 - 2 = 10$$',
  },
  {
    id: 'b6-44',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'Find the coordinates of the stationary point of the curve $y = x^2 - 8x + 5$ and determine its nature.',
    markScheme: '$\\dfrac{dy}{dx} = 2x - 8 = 0 \\Rightarrow x = 4$ ✓\n$y = 16 - 32 + 5 = -11$, so $(4, -11)$ ✓✓\n$\\dfrac{d^2y}{dx^2} = 2 > 0 \\Rightarrow$ minimum ✓',
    workedSolution: 'At a stationary point $\\dfrac{dy}{dx} = 0$:\n$$\\frac{dy}{dx} = 2x - 8 = 0 \\implies x = 4$$\n$$y = 4^2 - 8(4) + 5 = 16 - 32 + 5 = -11$$\nStationary point: $(4, -11)$. Since $\\dfrac{d^2y}{dx^2} = 2 > 0$, it is a minimum.',
  },
  {
    id: 'b6-45',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 4,
    body: 'Find the equation of the tangent to the curve $y = x^2 - 3x + 4$ at the point where $x = 2$.',
    markScheme: 'At $x = 2$: $y = 4 - 6 + 4 = 2$ ✓\n$\\dfrac{dy}{dx} = 2x - 3 = 1$ at $x = 2$ ✓\n$y - 2 = 1(x - 2)$ ✓\n$y = x$ ✓',
    workedSolution: 'Find the point: $y = 2^2 - 3(2) + 4 = 2$, so the point is $(2, 2)$.\n\nFind the gradient: $\\dfrac{dy}{dx} = 2x - 3$, which at $x = 2$ gives $1$.\n\nEquation of the tangent:\n$$y - 2 = 1(x - 2) \\implies y = x$$',
  },

  // ── Trigonometry ──
  {
    id: 'b6-46',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Convert $120°$ to radians, giving your answer in terms of $\\pi$.',
    markScheme: '$120 \\times \\dfrac{\\pi}{180}$ ✓\n$= \\dfrac{2\\pi}{3}$ ✓',
    workedSolution: 'Multiply by $\\dfrac{\\pi}{180}$:\n$$120° = 120 \\times \\frac{\\pi}{180} = \\frac{2\\pi}{3}$$',
  },
  {
    id: 'b6-47',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'A sector of a circle has radius $6$ cm and angle $0.5$ radians. Find the arc length.',
    markScheme: '$s = r\\theta = 6 \\times 0.5$ ✓\n$= 3$ cm ✓',
    workedSolution: 'Using $s = r\\theta$ with $r = 6$ and $\\theta = 0.5$:\n$$s = 6 \\times 0.5 = 3 \\text{ cm}$$',
  },
  {
    id: 'b6-48',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the area of a sector with radius $10$ cm and angle $\\dfrac{\\pi}{4}$ radians. Give your answer in terms of $\\pi$.',
    markScheme: '$A = \\dfrac{1}{2}r^2\\theta = \\dfrac{1}{2}(100)\\dfrac{\\pi}{4}$ ✓✓\n$= \\dfrac{25\\pi}{2}$ cm$^2$ ✓',
    workedSolution: 'Using $A = \\dfrac{1}{2}r^2\\theta$ with $r = 10$ and $\\theta = \\dfrac{\\pi}{4}$:\n$$A = \\frac{1}{2}(10)^2 \\times \\frac{\\pi}{4} = \\frac{1}{2}(100)\\frac{\\pi}{4} = \\frac{25\\pi}{2} \\text{ cm}^2$$',
  },
  {
    id: 'b6-49',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $2\\sin x = 1$ for $0° \\leq x \\leq 360°$.',
    markScheme: '$\\sin x = \\dfrac{1}{2}$ ✓\n$x = 30°$ ✓\n$x = 150°$ ✓',
    workedSolution: 'Rearrange:\n$$\\sin x = \\frac{1}{2}$$\nThe principal value is $x = 30°$. Sine is also positive in the second quadrant:\n$$x = 180° - 30° = 150°$$\nSolutions: $x = 30°, 150°$.',
  },
  {
    id: 'b6-50',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 4,
    body: 'In triangle $ABC$, $a = 7$, $b = 8$ and angle $C = 60°$. Find the length of side $c$, giving your answer to 3 significant figures.',
    markScheme: 'Cosine rule: $c^2 = 7^2 + 8^2 - 2(7)(8)\\cos 60°$ ✓\n$c^2 = 113 - 56 = 57$ ✓✓\n$c = 7.55$ (3 s.f.) ✓',
    workedSolution: 'Apply the cosine rule $c^2 = a^2 + b^2 - 2ab\\cos C$:\n$$c^2 = 7^2 + 8^2 - 2(7)(8)\\cos 60° = 49 + 64 - 112 \\times 0.5$$\n$$c^2 = 113 - 56 = 57$$\n$$c = \\sqrt{57} = 7.55 \\text{ (3 s.f.)}$$',
  },
];
