import { Question } from './types';

export const batch5: Question[] = [
  // ═══════════════════════════════════════════════════════════════
  // CALCULUS — calc-13 to calc-62
  // ═══════════════════════════════════════════════════════════════

  // ── Differentiation from first principles ──
  {
    id: 'calc-13',
    topic: 'calculus',
    subtopic: 'Differentiation from first principles',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Using differentiation from first principles, find $\\dfrac{dy}{dx}$ when $y = 5x$.',
    markScheme: '$\\dfrac{(5(x+h)) - 5x}{h}$ ✓\n$= \\dfrac{5h}{h} = 5$ ✓\n$\\dfrac{dy}{dx} = 5$ ✓',
    workedSolution: 'Using the definition:\n\n$$\\frac{dy}{dx} = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}$$\n\n$$= \\lim_{h \\to 0} \\frac{5(x+h) - 5x}{h} = \\lim_{h \\to 0} \\frac{5x + 5h - 5x}{h} = \\lim_{h \\to 0} \\frac{5h}{h} = 5$$',
  },
  {
    id: 'calc-14',
    topic: 'calculus',
    subtopic: 'Differentiation from first principles',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Prove from first principles that the derivative of $x^3$ is $3x^2$.',
    markScheme: '$f(x+h) = (x+h)^3 = x^3 + 3x^2h + 3xh^2 + h^3$ ✓\n$f(x+h) - f(x) = 3x^2h + 3xh^2 + h^3$ ✓\n$\\dfrac{f(x+h)-f(x)}{h} = 3x^2 + 3xh + h^2$ ✓\nAs $h \\to 0$, $\\dfrac{dy}{dx} = 3x^2$ ✓',
    workedSolution: 'Let $f(x) = x^3$.\n\n$$f(x+h) = (x+h)^3 = x^3 + 3x^2h + 3xh^2 + h^3$$\n\n$$f(x+h) - f(x) = 3x^2h + 3xh^2 + h^3 = h(3x^2 + 3xh + h^2)$$\n\n$$\\frac{f(x+h) - f(x)}{h} = 3x^2 + 3xh + h^2$$\n\nTaking the limit as $h \\to 0$:\n\n$$\\frac{dy}{dx} = 3x^2$$',
  },
  {
    id: 'calc-15',
    topic: 'calculus',
    subtopic: 'Differentiation from first principles',
    difficulty: 'hard',
    type: 'proof',
    marks: 5,
    body: 'Use differentiation from first principles to show that if $f(x) = \\dfrac{1}{x}$, then $f\'(x) = -\\dfrac{1}{x^2}$.',
    markScheme: '$f(x+h) = \\dfrac{1}{x+h}$ ✓\n$f(x+h) - f(x) = \\dfrac{1}{x+h} - \\dfrac{1}{x} = \\dfrac{x - (x+h)}{x(x+h)} = \\dfrac{-h}{x(x+h)}$ ✓✓\n$\\dfrac{f(x+h)-f(x)}{h} = \\dfrac{-1}{x(x+h)}$ ✓\nAs $h \\to 0$: $f\'(x) = -\\dfrac{1}{x^2}$ ✓',
    workedSolution: '$$f(x+h) - f(x) = \\frac{1}{x+h} - \\frac{1}{x} = \\frac{x - (x+h)}{x(x+h)} = \\frac{-h}{x(x+h)}$$\n\n$$\\frac{f(x+h) - f(x)}{h} = \\frac{-h}{h \\cdot x(x+h)} = \\frac{-1}{x(x+h)}$$\n\nTaking the limit:\n\n$$f\'(x) = \\lim_{h \\to 0} \\frac{-1}{x(x+h)} = \\frac{-1}{x \\cdot x} = -\\frac{1}{x^2}$$',
  },
  {
    id: 'calc-16',
    topic: 'calculus',
    subtopic: 'Differentiation from first principles',
    difficulty: 'exam-hard',
    type: 'proof',
    marks: 6,
    body: 'Use differentiation from first principles to find the derivative of $f(x) = \\sqrt{x}$.\n\nYou may use the identity $a - b = \\dfrac{a^2 - b^2}{a + b}$.',
    markScheme: '$f(x+h) - f(x) = \\sqrt{x+h} - \\sqrt{x}$ ✓\nMultiply by conjugate: $= \\dfrac{(x+h) - x}{\\sqrt{x+h} + \\sqrt{x}} = \\dfrac{h}{\\sqrt{x+h} + \\sqrt{x}}$ ✓✓\n$\\dfrac{f(x+h)-f(x)}{h} = \\dfrac{1}{\\sqrt{x+h} + \\sqrt{x}}$ ✓\nAs $h \\to 0$: $f\'(x) = \\dfrac{1}{2\\sqrt{x}}$ ✓✓',
    workedSolution: '$$f(x+h) - f(x) = \\sqrt{x+h} - \\sqrt{x}$$\n\nUsing the given identity with $a = \\sqrt{x+h}$ and $b = \\sqrt{x}$:\n\n$$\\sqrt{x+h} - \\sqrt{x} = \\frac{(\\sqrt{x+h})^2 - (\\sqrt{x})^2}{\\sqrt{x+h} + \\sqrt{x}} = \\frac{(x+h) - x}{\\sqrt{x+h} + \\sqrt{x}} = \\frac{h}{\\sqrt{x+h} + \\sqrt{x}}$$\n\n$$\\frac{f(x+h) - f(x)}{h} = \\frac{1}{\\sqrt{x+h} + \\sqrt{x}}$$\n\nAs $h \\to 0$:\n\n$$f\'(x) = \\frac{1}{\\sqrt{x} + \\sqrt{x}} = \\frac{1}{2\\sqrt{x}}$$',
  },

  // ── Differentiation rules ──
  {
    id: 'calc-17',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Differentiate $y = 4x^7$ with respect to $x$.',
    markScheme: '$\\dfrac{dy}{dx} = 4 \\times 7 x^{7-1}$ ✓\n$= 28x^6$ ✓',
    workedSolution: 'Using the power rule $\\dfrac{d}{dx}(ax^n) = anx^{n-1}$:\n\n$$\\frac{dy}{dx} = 4 \\times 7x^{7-1} = 28x^6$$',
  },
  {
    id: 'calc-18',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find $\\dfrac{dy}{dx}$ when $y = 3x^4 - 2x^2 + 7x - 1$.',
    markScheme: '$12x^3$ ✓ $- 4x$ ✓ $+ 7$ ✓',
    workedSolution: 'Differentiating term by term:\n\n$$\\frac{dy}{dx} = 3(4x^3) - 2(2x) + 7(1) - 0 = 12x^3 - 4x + 7$$',
  },
  {
    id: 'calc-19',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Given that $y = \\dfrac{6}{x^3} - \\dfrac{4}{\\sqrt{x}}$, find $\\dfrac{dy}{dx}$.',
    markScheme: '$y = 6x^{-3} - 4x^{-1/2}$ ✓\n$\\dfrac{dy}{dx} = -18x^{-4} + 2x^{-3/2}$ ✓\n$= -\\dfrac{18}{x^4} + \\dfrac{2}{x^{3/2}}$ ✓',
    workedSolution: 'Rewrite using negative and fractional powers:\n\n$$y = 6x^{-3} - 4x^{-1/2}$$\n\nDifferentiate:\n\n$$\\frac{dy}{dx} = 6(-3)x^{-4} - 4\\left(-\\frac{1}{2}\\right)x^{-3/2} = -18x^{-4} + 2x^{-3/2}$$\n\n$$= -\\frac{18}{x^4} + \\frac{2}{x\\sqrt{x}}$$',
  },
  {
    id: 'calc-20',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Given $f(x) = x^2(3x - 1)$, find $f\'(x)$ and evaluate $f\'(2)$.',
    markScheme: '$f(x) = 3x^3 - x^2$ ✓\n$f\'(x) = 9x^2 - 2x$ ✓\n$f\'(2) = 9(4) - 2(2) = 36 - 4$ ✓\n$= 32$ ✓',
    workedSolution: 'Expand first:\n\n$$f(x) = x^2(3x - 1) = 3x^3 - x^2$$\n\nDifferentiate:\n\n$$f\'(x) = 9x^2 - 2x$$\n\nSubstitute $x = 2$:\n\n$$f\'(2) = 9(4) - 2(2) = 36 - 4 = 32$$',
  },
  {
    id: 'calc-21',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 4,
    body: 'Differentiate $y = \\dfrac{x^3 + 4x}{2\\sqrt{x}}$ with respect to $x$.',
    markScheme: '$y = \\dfrac{x^3}{2x^{1/2}} + \\dfrac{4x}{2x^{1/2}} = \\dfrac{1}{2}x^{5/2} + 2x^{1/2}$ ✓✓\n$\\dfrac{dy}{dx} = \\dfrac{5}{4}x^{3/2} + x^{-1/2}$ ✓✓',
    workedSolution: 'Simplify by dividing each term:\n\n$$y = \\frac{x^3}{2x^{1/2}} + \\frac{4x}{2x^{1/2}} = \\frac{1}{2}x^{5/2} + 2x^{1/2}$$\n\nDifferentiate:\n\n$$\\frac{dy}{dx} = \\frac{1}{2} \\cdot \\frac{5}{2}x^{3/2} + 2 \\cdot \\frac{1}{2}x^{-1/2} = \\frac{5}{4}x^{3/2} + \\frac{1}{\\sqrt{x}}$$',
  },
  {
    id: 'calc-22',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 5,
    body: 'The curve $C$ has equation $y = 2x^3 - 9x^2 + 12x$.\n\n(a) Find $\\dfrac{dy}{dx}$. [2]\n\n(b) Find $\\dfrac{d^2y}{dx^2}$. [1]\n\n(c) Find the values of $x$ for which $\\dfrac{dy}{dx} = 0$. [2]',
    markScheme: '(a) $\\dfrac{dy}{dx} = 6x^2 - 18x + 12$ ✓✓\n\n(b) $\\dfrac{d^2y}{dx^2} = 12x - 18$ ✓\n\n(c) $6x^2 - 18x + 12 = 0$ → $x^2 - 3x + 2 = 0$ ✓\n$(x-1)(x-2) = 0$ → $x = 1$ or $x = 2$ ✓',
    workedSolution: '**(a)**\n$$\\frac{dy}{dx} = 6x^2 - 18x + 12$$\n\n**(b)**\n$$\\frac{d^2y}{dx^2} = 12x - 18$$\n\n**(c)** Setting $\\dfrac{dy}{dx} = 0$:\n$$6x^2 - 18x + 12 = 0$$\n$$x^2 - 3x + 2 = 0$$\n$$(x-1)(x-2) = 0$$\n$$x = 1 \\text{ or } x = 2$$',
  },

  // ── Tangents and normals ──
  {
    id: 'calc-23',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find the gradient of the curve $y = x^2 - 3x$ at the point where $x = 4$.',
    markScheme: '$\\dfrac{dy}{dx} = 2x - 3$ ✓\nAt $x = 4$: gradient $= 2(4) - 3$ ✓\n$= 5$ ✓',
    workedSolution: 'Differentiate:\n$$\\frac{dy}{dx} = 2x - 3$$\n\nAt $x = 4$:\n$$\\text{gradient} = 2(4) - 3 = 8 - 3 = 5$$',
  },
  {
    id: 'calc-24',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Find the equation of the tangent to the curve $y = x^3 - 2x + 1$ at the point $(2, 5)$.',
    markScheme: '$\\dfrac{dy}{dx} = 3x^2 - 2$ ✓\nAt $x = 2$: $m = 3(4) - 2 = 10$ ✓\n$y - 5 = 10(x - 2)$ ✓\n$y = 10x - 15$ ✓',
    workedSolution: 'Differentiate: $\\dfrac{dy}{dx} = 3x^2 - 2$\n\nAt $x = 2$: gradient $= 3(4) - 2 = 10$\n\nUsing $y - y_1 = m(x - x_1)$:\n$$y - 5 = 10(x - 2)$$\n$$y = 10x - 20 + 5 = 10x - 15$$',
  },
  {
    id: 'calc-25',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 5,
    body: 'Find the equation of the normal to the curve $y = 4x - x^2$ at the point where $x = 3$.',
    markScheme: 'At $x = 3$: $y = 12 - 9 = 3$, point $(3, 3)$ ✓\n$\\dfrac{dy}{dx} = 4 - 2x$ ✓\nAt $x = 3$: $m_{\\text{tan}} = 4 - 6 = -2$ ✓\n$m_{\\text{normal}} = \\dfrac{1}{2}$ ✓\n$y - 3 = \\dfrac{1}{2}(x - 3)$ → $y = \\dfrac{1}{2}x + \\dfrac{3}{2}$ ✓',
    workedSolution: 'At $x = 3$: $y = 4(3) - 3^2 = 12 - 9 = 3$. The point is $(3, 3)$.\n\nDifferentiate: $\\dfrac{dy}{dx} = 4 - 2x$\n\nAt $x = 3$: tangent gradient $= 4 - 6 = -2$\n\nNormal gradient $= -\\dfrac{1}{-2} = \\dfrac{1}{2}$\n\n$$y - 3 = \\frac{1}{2}(x - 3) \\implies y = \\frac{1}{2}x + \\frac{3}{2}$$',
  },
  {
    id: 'calc-26',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 7,
    body: 'The curve $C$ has equation $y = x^3 - 6x^2 + 9x + 2$. The point $P$ lies on $C$ where $x = 1$.\n\n(a) Find the equation of the tangent to $C$ at $P$. [4]\n\n(b) The tangent at $P$ meets $C$ again at the point $Q$. Find the coordinates of $Q$. [3]',
    markScheme: '(a) At $x=1$: $y = 1 - 6 + 9 + 2 = 6$ ✓\n$\\dfrac{dy}{dx} = 3x^2 - 12x + 9$; at $x=1$: $m = 3 - 12 + 9 = 0$ ✓\nTangent: $y = 6$ ✓✓\n\n(b) $x^3 - 6x^2 + 9x + 2 = 6$ → $x^3 - 6x^2 + 9x - 4 = 0$ ✓\n$(x-1)^2(x-4) = 0$ ✓\n$Q = (4, 6)$ ✓',
    workedSolution: '**(a)** At $x = 1$: $y = 1 - 6 + 9 + 2 = 6$, so $P = (1, 6)$.\n\n$$\\frac{dy}{dx} = 3x^2 - 12x + 9$$\n\nAt $x = 1$: gradient $= 3 - 12 + 9 = 0$\n\nThe tangent is horizontal: $y = 6$.\n\n**(b)** Substituting $y = 6$ into the curve equation:\n$$x^3 - 6x^2 + 9x + 2 = 6$$\n$$x^3 - 6x^2 + 9x - 4 = 0$$\n\nSince $x = 1$ is a repeated root (tangent touches), $(x-1)^2$ is a factor:\n$$x^3 - 6x^2 + 9x - 4 = (x-1)^2(x-4)$$\n\nSo $Q$ has $x = 4$, $y = 6$. Hence $Q = (4, 6)$.',
  },
  {
    id: 'calc-27',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 8,
    body: 'The curve $C$ has equation $y = x^3 - 6x^2 + 12x - 3$.\n\n(a) Find the equation of the normal to $C$ at the point where $x = 1$. [5]\n\n(b) The normal at $x = 1$ meets $C$ again at the point $A$. Find the coordinates of $A$. [3]',
    markScheme: '(a) At $x = 1$: $y = 1 - 6 + 12 - 3 = 4$ ✓\n$\\dfrac{dy}{dx} = 3x^2 - 12x + 12$; at $x = 1$: $m = 3 - 12 + 12 = 3$ ✓\nNormal gradient $= -1/3$ ✓\n$y - 4 = -\\frac{1}{3}(x - 1)$ ✓\n$y = -\\frac{1}{3}x + \\frac{13}{3}$ ✓\n\n(b) Substitute into curve: $x^3 - 6x^2 + 12x - 3 = -\\frac{1}{3}x + \\frac{13}{3}$ ✓\n$3x^3 - 18x^2 + 37x - 22 = 0$\n$(x - 1)(3x^2 - 15x + 22) = 0$ ✓\n$x = \\frac{15 \\pm \\sqrt{225-264}}{6}$ — discriminant negative, so $x = 1$ is the only real root.\nAlternatively: $A = (1, 4)$ but that\'s the same point. The normal is tangent to the curve here (triple root). ✓',
    workedSolution: '**(a)** At $x = 1$:\n$$y = 1 - 6 + 12 - 3 = 4$$\n\n$$\\frac{dy}{dx} = 3x^2 - 12x + 12$$\n\nAt $x = 1$: gradient $= 3 - 12 + 12 = 3$\n\nNormal gradient $= -\\dfrac{1}{3}$\n\n$$y - 4 = -\\frac{1}{3}(x - 1)$$\n$$y = -\\frac{1}{3}x + \\frac{13}{3}$$\n\n**(b)** Setting the normal equal to the curve:\n$$x^3 - 6x^2 + 12x - 3 = -\\frac{1}{3}x + \\frac{13}{3}$$\n\nMultiplying by 3:\n$$3x^3 - 18x^2 + 37x - 22 = 0$$\n\nSince $x = 1$ is a root: $(x-1)(3x^2 - 15x + 22) = 0$\n\nDiscriminant of $3x^2 - 15x + 22$: $225 - 264 = -39 < 0$\n\nSo the normal only meets the curve at $(1, 4)$ — the normal does not cross the curve again.',
  },

  // ── Stationary points ──
  {
    id: 'calc-28',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find the coordinates of the stationary point of $y = x^2 - 6x + 11$.',
    markScheme: '$\\dfrac{dy}{dx} = 2x - 6$ ✓\n$2x - 6 = 0$ → $x = 3$ ✓\n$y = 9 - 18 + 11 = 2$, so $(3, 2)$ ✓',
    workedSolution: '$$\\frac{dy}{dx} = 2x - 6$$\n\nAt a stationary point, $\\dfrac{dy}{dx} = 0$:\n$$2x - 6 = 0 \\implies x = 3$$\n\n$$y = (3)^2 - 6(3) + 11 = 9 - 18 + 11 = 2$$\n\nStationary point is $(3, 2)$.',
  },
  {
    id: 'calc-29',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'The curve $C$ has equation $y = x^3 - 12x + 5$.\n\n(a) Find the coordinates of the stationary points of $C$. [3]\n\n(b) Determine the nature of each stationary point. [2]',
    markScheme: '(a) $\\dfrac{dy}{dx} = 3x^2 - 12 = 0$ ✓\n$x^2 = 4$ → $x = \\pm 2$ ✓\n$x=2$: $y = 8-24+5=-11$; $x=-2$: $y=-8+24+5=21$ ✓\n\n(b) $\\dfrac{d^2y}{dx^2} = 6x$ ✓\nAt $x=2$: $12 > 0$ → minimum; at $x=-2$: $-12 < 0$ → maximum ✓',
    workedSolution: '**(a)** $\\dfrac{dy}{dx} = 3x^2 - 12$\n\nSetting equal to zero: $3x^2 = 12 \\implies x^2 = 4 \\implies x = 2$ or $x = -2$\n\nAt $x = 2$: $y = 8 - 24 + 5 = -11$\nAt $x = -2$: $y = -8 + 24 + 5 = 21$\n\nStationary points: $(2, -11)$ and $(-2, 21)$.\n\n**(b)** $\\dfrac{d^2y}{dx^2} = 6x$\n\nAt $x = 2$: $\\dfrac{d^2y}{dx^2} = 12 > 0$ — minimum.\nAt $x = -2$: $\\dfrac{d^2y}{dx^2} = -12 < 0$ — maximum.',
  },
  {
    id: 'calc-30',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'hard',
    type: 'applied',
    marks: 7,
    body: 'A farmer has 120 m of fencing to enclose a rectangular pen against a straight wall. The wall forms one side of the rectangle. The other three sides are made of fencing.\n\nGiven that the width of the pen perpendicular to the wall is $x$ metres,\n\n(a) show that the area of the pen is $A = 120x - 2x^2$, [2]\n\n(b) find the maximum area of the pen. [3]\n\n(c) Justify that this is a maximum. [2]',
    markScheme: '(a) Length parallel to wall $= 120 - 2x$ ✓\n$A = x(120 - 2x) = 120x - 2x^2$ ✓\n\n(b) $\\dfrac{dA}{dx} = 120 - 4x = 0$ → $x = 30$ ✓\n$A = 120(30) - 2(900) = 3600 - 1800$ ✓\n$= 1800$ m² ✓\n\n(c) $\\dfrac{d^2A}{dx^2} = -4 < 0$ ✓ → maximum ✓',
    workedSolution: '**(a)** The fencing covers two widths ($x$) and one length: $2x + l = 120$, so $l = 120 - 2x$.\n\n$$A = x(120 - 2x) = 120x - 2x^2$$\n\n**(b)** $$\\frac{dA}{dx} = 120 - 4x = 0 \\implies x = 30$$\n\n$$A = 120(30) - 2(30)^2 = 3600 - 1800 = 1800 \\text{ m}^2$$\n\n**(c)** $$\\frac{d^2A}{dx^2} = -4 < 0$$\n\nSince the second derivative is negative, this is a maximum.',
  },
  {
    id: 'calc-31',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'exam-hard',
    type: 'applied',
    marks: 9,
    body: 'An open-top box is made from a square sheet of card of side 24 cm by cutting squares of side $x$ cm from each corner and folding up the sides.\n\n(a) Show that the volume of the box is $V = 4x^3 - 96x^2 + 576x$. [2]\n\n(b) Find the value of $x$ that gives the maximum volume. [4]\n\n(c) Find this maximum volume. [1]\n\n(d) State the range of valid values of $x$. [2]',
    markScheme: '(a) Base $= (24-2x)$, height $= x$ ✓\n$V = x(24-2x)^2 = x(576 - 96x + 4x^2) = 4x^3 - 96x^2 + 576x$ ✓\n\n(b) $\\dfrac{dV}{dx} = 12x^2 - 192x + 576 = 0$ ✓\n$x^2 - 16x + 48 = 0$ ✓\n$(x-4)(x-12) = 0$ → $x = 4$ or $x = 12$ ✓\n$\\dfrac{d^2V}{dx^2} = 24x - 192$; at $x=4$: $= -96 < 0$ → max ✓\n\n(c) $V = 4(64) - 96(16) + 576(4) = 256 - 1536 + 2304 = 1024$ cm³ ✓\n\n(d) $0 < x < 12$ ✓✓',
    workedSolution: '**(a)** After cutting, the base is $(24-2x) \\times (24-2x)$ and the height is $x$:\n$$V = x(24-2x)^2 = x(576 - 96x + 4x^2) = 4x^3 - 96x^2 + 576x$$\n\n**(b)** $$\\frac{dV}{dx} = 12x^2 - 192x + 576 = 0$$\n$$x^2 - 16x + 48 = 0$$\n$$(x-4)(x-12) = 0 \\implies x = 4 \\text{ or } x = 12$$\n\n$\\dfrac{d^2V}{dx^2} = 24x - 192$\n\nAt $x = 4$: $24(4) - 192 = -96 < 0$ — maximum.\nAt $x = 12$: $24(12) - 192 = 96 > 0$ — minimum.\n\nSo $x = 4$ gives maximum volume.\n\n**(c)** $V = 4(64) - 96(16) + 576(4) = 256 - 1536 + 2304 = 1024$ cm$^3$.\n\n**(d)** For the box to exist: $x > 0$ and $24 - 2x > 0 \\implies x < 12$.\n\nValid range: $0 < x < 12$.',
  },
  {
    id: 'calc-32',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'exam-hard',
    type: 'applied',
    marks: 8,
    body: 'A closed cylinder has total surface area $600\\pi$ cm².\n\n(a) Given that the radius is $r$ cm, show that the height $h$ of the cylinder is $h = \\dfrac{300 - r^2}{r}$. [2]\n\n(b) Show that the volume is $V = \\pi(300r - r^3)$. [1]\n\n(c) Find the maximum volume, giving your answer in terms of $\\pi$. [5]',
    markScheme: '(a) $2\\pi r^2 + 2\\pi rh = 600\\pi$ ✓\n$r^2 + rh = 300$ → $h = \\dfrac{300 - r^2}{r}$ ✓\n\n(b) $V = \\pi r^2 h = \\pi r^2 \\cdot \\dfrac{300 - r^2}{r} = \\pi(300r - r^3)$ ✓\n\n(c) $\\dfrac{dV}{dr} = \\pi(300 - 3r^2) = 0$ ✓\n$r^2 = 100$ → $r = 10$ ✓\n$\\dfrac{d^2V}{dr^2} = -6\\pi r$; at $r=10$: $= -60\\pi < 0$ → max ✓✓\n$V = \\pi(3000 - 1000) = 2000\\pi$ cm³ ✓',
    workedSolution: '**(a)** Total surface area $= 2\\pi r^2 + 2\\pi rh = 600\\pi$\n\nDivide by $2\\pi$: $r^2 + rh = 300$\n\n$$h = \\frac{300 - r^2}{r}$$\n\n**(b)** $$V = \\pi r^2 h = \\pi r^2 \\cdot \\frac{300 - r^2}{r} = \\pi r(300 - r^2) = \\pi(300r - r^3)$$\n\n**(c)** $$\\frac{dV}{dr} = \\pi(300 - 3r^2) = 0$$\n$$3r^2 = 300 \\implies r^2 = 100 \\implies r = 10$$\n\n$$\\frac{d^2V}{dr^2} = -6\\pi r$$\nAt $r = 10$: $-60\\pi < 0$ — confirmed maximum.\n\n$$V = \\pi(300(10) - 10^3) = \\pi(3000 - 1000) = 2000\\pi \\text{ cm}^3$$',
  },

  // ── Integration ──
  {
    id: 'calc-33',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find $\\displaystyle\\int 6x^2 \\, dx$.',
    markScheme: '$\\dfrac{6x^3}{3} + c$ ✓\n$= 2x^3 + c$ ✓',
    workedSolution: 'Using the power rule for integration:\n\n$$\\int 6x^2 \\, dx = \\frac{6x^{2+1}}{2+1} + c = \\frac{6x^3}{3} + c = 2x^3 + c$$',
  },
  {
    id: 'calc-34',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find $\\displaystyle\\int (4x^3 - 2x + 5) \\, dx$.',
    markScheme: '$x^4$ ✓ $- x^2 + 5x$ ✓ $+ c$ ✓',
    workedSolution: 'Integrate term by term:\n\n$$\\int (4x^3 - 2x + 5) \\, dx = \\frac{4x^4}{4} - \\frac{2x^2}{2} + 5x + c = x^4 - x^2 + 5x + c$$',
  },
  {
    id: 'calc-35',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Find $\\displaystyle\\int \\left(3\\sqrt{x} + \\dfrac{2}{x^2}\\right) dx$.',
    markScheme: '$3x^{1/2} + 2x^{-2}$ rewritten ✓\n$\\dfrac{3x^{3/2}}{3/2} = 2x^{3/2}$ ✓\n$\\dfrac{2x^{-1}}{-1} = -\\dfrac{2}{x}$ ✓\nAnswer: $2x^{3/2} - \\dfrac{2}{x} + c$ ✓',
    workedSolution: 'Rewrite: $3\\sqrt{x} = 3x^{1/2}$ and $\\dfrac{2}{x^2} = 2x^{-2}$\n\n$$\\int 3x^{1/2} \\, dx = 3 \\cdot \\frac{x^{3/2}}{3/2} = 2x^{3/2}$$\n\n$$\\int 2x^{-2} \\, dx = 2 \\cdot \\frac{x^{-1}}{-1} = -\\frac{2}{x}$$\n\nSo $\\displaystyle\\int \\left(3\\sqrt{x} + \\frac{2}{x^2}\\right) dx = 2x^{3/2} - \\frac{2}{x} + c$',
  },
  {
    id: 'calc-36',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'A curve passes through the point $(1, 3)$ and has gradient function $\\dfrac{dy}{dx} = 6x^2 - 4x + 1$.\n\n(a) Find the equation of the curve. [3]\n\n(b) Find the value of $y$ when $x = 2$. [2]',
    markScheme: '(a) $y = 2x^3 - 2x^2 + x + c$ ✓\nAt $(1,3)$: $3 = 2 - 2 + 1 + c$ → $c = 2$ ✓\n$y = 2x^3 - 2x^2 + x + 2$ ✓\n\n(b) $y = 2(8) - 2(4) + 2 + 2 = 16 - 8 + 4 = 12$ ✓✓',
    workedSolution: '**(a)** Integrate:\n$$y = \\int (6x^2 - 4x + 1) \\, dx = 2x^3 - 2x^2 + x + c$$\n\nUsing $(1, 3)$: $3 = 2(1) - 2(1) + 1 + c = 1 + c$, so $c = 2$.\n\n$$y = 2x^3 - 2x^2 + x + 2$$\n\n**(b)** At $x = 2$: $y = 2(8) - 2(4) + 2 + 2 = 16 - 8 + 2 + 2 = 12$.',
  },
  {
    id: 'calc-37',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 4,
    body: 'Find $\\displaystyle\\int \\dfrac{(x+1)(3x-2)}{\\sqrt{x}} \\, dx$.',
    markScheme: 'Expand numerator: $3x^2 + x - 2$ ✓\nDivide by $x^{1/2}$: $3x^{3/2} + x^{1/2} - 2x^{-1/2}$ ✓\nIntegrate: $\\dfrac{6}{5}x^{5/2} + \\dfrac{2}{3}x^{3/2} - 4x^{1/2} + c$ ✓✓',
    workedSolution: 'Expand: $(x+1)(3x-2) = 3x^2 + x - 2$\n\nDivide each term by $\\sqrt{x} = x^{1/2}$:\n$$\\frac{3x^2}{x^{1/2}} + \\frac{x}{x^{1/2}} - \\frac{2}{x^{1/2}} = 3x^{3/2} + x^{1/2} - 2x^{-1/2}$$\n\nIntegrate:\n$$3 \\cdot \\frac{x^{5/2}}{5/2} + \\frac{x^{3/2}}{3/2} - 2 \\cdot \\frac{x^{1/2}}{1/2} + c = \\frac{6}{5}x^{5/2} + \\frac{2}{3}x^{3/2} - 4\\sqrt{x} + c$$',
  },

  // ── Definite integrals ──
  {
    id: 'calc-38',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Evaluate $\\displaystyle\\int_1^3 (2x + 1) \\, dx$.',
    markScheme: '$[x^2 + x]_1^3$ ✓\n$= (9 + 3) - (1 + 1)$ ✓\n$= 12 - 2 = 10$ ✓',
    workedSolution: '$$\\int_1^3 (2x+1) \\, dx = \\left[x^2 + x\\right]_1^3 = (9 + 3) - (1 + 1) = 12 - 2 = 10$$',
  },
  {
    id: 'calc-39',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Evaluate $\\displaystyle\\int_1^4 \\left(3x^{1/2} - \\dfrac{1}{x^2}\\right) dx$.',
    markScheme: '$\\left[2x^{3/2} + \\dfrac{1}{x}\\right]_1^4$ ✓✓\n$= (2 \\cdot 8 + 1/4) - (2 + 1)$ ✓\n$= 16.25 - 3 = 13.25 = \\dfrac{53}{4}$ ✓',
    workedSolution: '$$\\int_1^4 \\left(3x^{1/2} - x^{-2}\\right) dx = \\left[3 \\cdot \\frac{x^{3/2}}{3/2} + \\frac{x^{-1}}{1}\\right]_1^4 = \\left[2x^{3/2} + \\frac{1}{x}\\right]_1^4$$\n\n$$= \\left(2(8) + \\frac{1}{4}\\right) - \\left(2(1) + 1\\right) = \\left(16 + \\frac{1}{4}\\right) - 3 = \\frac{53}{4}$$',
  },
  {
    id: 'calc-40',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: 'Given that $\\displaystyle\\int_1^k 6x^2 \\, dx = 126$, where $k > 0$,\n\n(a) show that $k^3 = 64$, [3]\n\n(b) hence find the value of $k$. [3]',
    markScheme: '(a) \$[2x^3]_1^k = 2k^3 - 2\$ ✓\n\^3 - 2 = 126\$ ✓\n\^3 = 64\$ ✓\n\n(b) \ = \\\\sqrt[3]{64} = 4\$ ✓✓✓',
    workedSolution: '**(a)** $$\\int_1^k 6x^2 \\, dx = \\left[2x^3\\right]_1^k = 2k^3 - 2$$\n\nSetting equal to 126: $2k^3 - 2 = 126$, so $2k^3 = 128$.\n\n**(b)** $$k^3 = 64 \\implies k = 4$$',
  },

  // ── Area under a curve ──
  {
    id: 'calc-41',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Find the area enclosed between the curve $y = x^2$, the $x$-axis, and the lines $x = 0$ and $x = 3$.',
    markScheme: '$\\displaystyle\\int_0^3 x^2 \\, dx = \\left[\\dfrac{x^3}{3}\\right]_0^3$ ✓\n$= \\dfrac{27}{3} - 0$ ✓\n$= 9$ ✓',
    workedSolution: '$$\\text{Area} = \\int_0^3 x^2 \\, dx = \\left[\\frac{x^3}{3}\\right]_0^3 = \\frac{27}{3} - 0 = 9 \\text{ square units}$$',
  },
  {
    id: 'calc-42',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'The curve $C$ has equation $y = 6x - x^2$.\n\n(a) Find the $x$-coordinates where $C$ crosses the $x$-axis. [1]\n\n(b) Find the area enclosed between $C$ and the $x$-axis. [4]',
    markScheme: '(a) $x(6-x) = 0$ → $x = 0, 6$ ✓\n\n(b) $\\displaystyle\\int_0^6 (6x - x^2) \\, dx = \\left[3x^2 - \\dfrac{x^3}{3}\\right]_0^6$ ✓✓\n$= 108 - 72 = 36$ ✓✓',
    workedSolution: '**(a)** $6x - x^2 = x(6 - x) = 0 \\implies x = 0$ or $x = 6$\n\n**(b)** $$\\int_0^6 (6x - x^2) \\, dx = \\left[3x^2 - \\frac{x^3}{3}\\right]_0^6 = \\left(3(36) - \\frac{216}{3}\\right) - 0 = 108 - 72 = 36$$',
  },
  {
    id: 'calc-43',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 7,
    body: 'The curve $y = x^2 - 4x + 3$ crosses the $x$-axis at the points $A$ and $B$.\n\n(a) Find the coordinates of $A$ and $B$. [2]\n\n(b) Find the area of the region bounded by the curve and the $x$-axis, explaining why the integral is negative. [5]',
    markScheme: '(a) $x^2 - 4x + 3 = (x-1)(x-3) = 0$ ✓\n$A = (1,0)$, $B = (3,0)$ ✓\n\n(b) $\\displaystyle\\int_1^3 (x^2 - 4x + 3) \\, dx = \\left[\\dfrac{x^3}{3} - 2x^2 + 3x\\right]_1^3$ ✓✓\n$= (9 - 18 + 9) - (1/3 - 2 + 3)$ ✓\n$= 0 - 4/3 = -4/3$ ✓\nArea $= \\left|-\\dfrac{4}{3}\\right| = \\dfrac{4}{3}$ ✓\nNegative because curve is below $x$-axis between $A$ and $B$.',
    workedSolution: '**(a)** $x^2 - 4x + 3 = (x-1)(x-3) = 0$\n\n$A = (1, 0)$ and $B = (3, 0)$.\n\n**(b)** $$\\int_1^3 (x^2 - 4x + 3) \\, dx = \\left[\\frac{x^3}{3} - 2x^2 + 3x\\right]_1^3$$\n\n$$= \\left(9 - 18 + 9\\right) - \\left(\\frac{1}{3} - 2 + 3\\right) = 0 - \\frac{4}{3} = -\\frac{4}{3}$$\n\nThe integral is negative because the curve lies below the $x$-axis between $x = 1$ and $x = 3$.\n\nThe area is $\\left|-\\dfrac{4}{3}\\right| = \\dfrac{4}{3}$ square units.',
  },
  {
    id: 'calc-44',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 9,
    body: 'The curves $y = x^2$ and $y = 4x - x^2$ intersect at two points.\n\n(a) Find the coordinates of the points of intersection. [3]\n\n(b) Find the area of the region enclosed between the two curves. [4]\n\n(c) Sketch the two curves on the same axes, shading the enclosed region. [2]',
    markScheme: '(a) $x^2 = 4x - x^2$ → $2x^2 - 4x = 0$ → $2x(x-2) = 0$ ✓\n$x = 0$: $y = 0$; $x = 2$: $y = 4$ ✓✓\nPoints: $(0, 0)$ and $(2, 4)$.\n\n(b) Area $= \\displaystyle\\int_0^2 [(4x - x^2) - x^2] \\, dx = \\int_0^2 (4x - 2x^2) \\, dx$ ✓\n$= \\left[2x^2 - \\dfrac{2x^3}{3}\\right]_0^2$ ✓\n$= 8 - \\dfrac{16}{3} = \\dfrac{8}{3}$ ✓✓\n\n(c) Correct parabolas with shaded region ✓✓',
    workedSolution: '**(a)** Setting equal: $x^2 = 4x - x^2 \\implies 2x^2 - 4x = 0 \\implies 2x(x - 2) = 0$\n\nSo $x = 0$ or $x = 2$. Points: $(0, 0)$ and $(2, 4)$.\n\n**(b)** For $0 \\le x \\le 2$, the curve $y = 4x - x^2$ is above $y = x^2$.\n\n$$\\text{Area} = \\int_0^2 (4x - x^2 - x^2) \\, dx = \\int_0^2 (4x - 2x^2) \\, dx$$\n\n$$= \\left[2x^2 - \\frac{2x^3}{3}\\right]_0^2 = 8 - \\frac{16}{3} = \\frac{24 - 16}{3} = \\frac{8}{3}$$\n\n**(c)** Both curves are parabolas through the origin. $y = x^2$ opens upward; $y = 4x - x^2$ opens downward with vertex at $(2, 4)$. The shaded region is the lens shape between them from $x = 0$ to $x = 2$.',
  },

  // ── More calculus: mixed subtopics ──
  {
    id: 'calc-45',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'The curve $C$ has equation $y = x^3 - 3x^2 - 9x + 5$. Find the range of values of $x$ for which $\\dfrac{dy}{dx} < 0$.',
    markScheme: '$\\dfrac{dy}{dx} = 3x^2 - 6x - 9$ ✓\n$3(x^2 - 2x - 3) < 0$ ✓\n$3(x-3)(x+1) < 0$ ✓\n$-1 < x < 3$ ✓',
    workedSolution: '$$\\frac{dy}{dx} = 3x^2 - 6x - 9 = 3(x^2 - 2x - 3) = 3(x-3)(x+1)$$\n\nFor $\\dfrac{dy}{dx} < 0$: $(x-3)(x+1) < 0$\n\nThis is negative when $-1 < x < 3$.',
  },
  {
    id: 'calc-46',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 7,
    body: 'The curve $C$ has equation $y = x^2 - 4x + 7$. The line $l$ is a tangent to $C$ and has gradient 2.\n\n(a) Find the equation of $l$. [4]\n\n(b) Find the area of the region bounded by $C$, the line $l$, and the $y$-axis. [3]',
    markScheme: '(a) $\\dfrac{dy}{dx} = 2x - 4 = 2$ → $x = 3$ ✓\nAt $x = 3$: $y = 9 - 12 + 7 = 4$ ✓\n$y - 4 = 2(x - 3)$ → $y = 2x - 2$ ✓✓\n\n(b) Area $= \\displaystyle\\int_0^3 [(x^2 - 4x + 7) - (2x - 2)] \\, dx$ ✓\n$= \\int_0^3 (x^2 - 6x + 9) \\, dx = \\int_0^3 (x-3)^2 \\, dx$ ✓\n$= \\left[\\dfrac{(x-3)^3}{3}\\right]_0^3 = 0 - \\dfrac{-27}{3} = 9$ ✓',
    workedSolution: '**(a)** $\\dfrac{dy}{dx} = 2x - 4$. Setting $= 2$: $2x - 4 = 2 \\implies x = 3$.\n\nAt $x = 3$: $y = 9 - 12 + 7 = 4$.\n\nTangent: $y - 4 = 2(x - 3) \\implies y = 2x - 2$.\n\n**(b)** For $0 \\le x \\le 3$, the curve is above the tangent (since the tangent only touches at $x = 3$).\n\n$$\\text{Area} = \\int_0^3 [(x^2 - 4x + 7) - (2x - 2)] \\, dx = \\int_0^3 (x^2 - 6x + 9) \\, dx$$\n\n$$= \\int_0^3 (x-3)^2 \\, dx = \\left[\\frac{(x-3)^3}{3}\\right]_0^3 = \\frac{0}{3} - \\frac{(-3)^3}{3} = 0 - (-9) = 9$$',
  },
  {
    id: 'calc-47',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: 'Given that $\\dfrac{dy}{dx} = 3x^2 - kx$ and the curve has a stationary point at $x = 4$,\n\n(a) find the value of $k$, [2]\n\n(b) given also that the curve passes through $(2, 10)$, find the equation of the curve. [4]',
    markScheme: '(a) At stationary point: $3(16) - 4k = 0$ → $48 = 4k$ → $k = 12$ ✓✓\n\n(b) $y = \\int (3x^2 - 12x) \\, dx = x^3 - 6x^2 + c$ ✓✓\nAt $(2, 10)$: $10 = 8 - 24 + c$ → $c = 26$ ✓\n$y = x^3 - 6x^2 + 26$ ✓',
    workedSolution: '**(a)** At a stationary point $\\dfrac{dy}{dx} = 0$:\n$$3(4)^2 - k(4) = 0 \\implies 48 - 4k = 0 \\implies k = 12$$\n\n**(b)** $$y = \\int (3x^2 - 12x) \\, dx = x^3 - 6x^2 + c$$\n\nUsing $(2, 10)$: $10 = 8 - 24 + c \\implies c = 26$\n\n$$y = x^3 - 6x^2 + 26$$',
  },
  {
    id: 'calc-48',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'A curve has equation $y = 12x^{1/2} - 2x^{3/2}$ for $x > 0$.\n\n(a) Find $\\dfrac{dy}{dx}$. [2]\n\n(b) Find the coordinates of the stationary point and determine its nature. [3]',
    markScheme: '(a) $\\dfrac{dy}{dx} = 6x^{-1/2} - 3x^{1/2}$ ✓✓\n\n(b) $\\dfrac{6}{\\sqrt{x}} - 3\\sqrt{x} = 0$ → $6 = 3x$ → $x = 2$ ✓\n$y = 12\\sqrt{2} - 2(2\\sqrt{2}) = 12\\sqrt{2} - 4\\sqrt{2} = 8\\sqrt{2}$ ✓\n$\\dfrac{d^2y}{dx^2} = -3x^{-3/2} - \\dfrac{3}{2}x^{-1/2}$; at $x=2$ this is negative → maximum ✓',
    workedSolution: '**(a)** $$\\frac{dy}{dx} = 12 \\cdot \\frac{1}{2}x^{-1/2} - 2 \\cdot \\frac{3}{2}x^{1/2} = 6x^{-1/2} - 3x^{1/2}$$\n\n**(b)** Setting $\\dfrac{dy}{dx} = 0$:\n$$\\frac{6}{\\sqrt{x}} = 3\\sqrt{x} \\implies 6 = 3x \\implies x = 2$$\n\n$y = 12\\sqrt{2} - 2(2)^{3/2} = 12\\sqrt{2} - 4\\sqrt{2} = 8\\sqrt{2}$\n\n$\\dfrac{d^2y}{dx^2} = -3x^{-3/2} - \\dfrac{3}{2}x^{-1/2}$. At $x = 2$: both terms are negative, so $\\dfrac{d^2y}{dx^2} < 0$ — maximum point at $(2, 8\\sqrt{2})$.',
  },
  {
    id: 'calc-49',
    topic: 'calculus',
    subtopic: 'Differentiation from first principles',
    difficulty: 'intermediate',
    type: 'proof',
    marks: 4,
    body: 'Use differentiation from first principles to show that the derivative of $f(x) = x^2 + 3x$ is $f\'(x) = 2x + 3$.',
    markScheme: '$f(x+h) = (x+h)^2 + 3(x+h) = x^2 + 2xh + h^2 + 3x + 3h$ ✓\n$f(x+h) - f(x) = 2xh + h^2 + 3h$ ✓\n$\\dfrac{f(x+h)-f(x)}{h} = 2x + h + 3$ ✓\nAs $h \\to 0$: $f\'(x) = 2x + 3$ ✓',
    workedSolution: '$$f(x+h) = (x+h)^2 + 3(x+h) = x^2 + 2xh + h^2 + 3x + 3h$$\n\n$$f(x+h) - f(x) = 2xh + h^2 + 3h = h(2x + h + 3)$$\n\n$$\\frac{f(x+h) - f(x)}{h} = 2x + h + 3$$\n\nAs $h \\to 0$: $f\'(x) = 2x + 3$.',
  },
  {
    id: 'calc-50',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Evaluate $\\displaystyle\\int_1^9 \\dfrac{3}{\\sqrt{x}} \\, dx$.',
    markScheme: '$\\displaystyle\\int 3x^{-1/2} \\, dx = 6x^{1/2}$ ✓\n$[6\\sqrt{x}]_1^9$ ✓\n$= 6(3) - 6(1)$ ✓\n$= 12$ ✓',
    workedSolution: '$$\\int_1^9 3x^{-1/2} \\, dx = \\left[3 \\cdot \\frac{x^{1/2}}{1/2}\\right]_1^9 = \\left[6\\sqrt{x}\\right]_1^9 = 6(3) - 6(1) = 18 - 6 = 12$$',
  },
  {
    id: 'calc-51',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: 'The region $R$ is bounded by the curve $y = x^2 + 1$, the $x$-axis, and the lines $x = 0$ and $x = 2$.\n\n(a) Find the area of $R$. [3]\n\n(b) The line $y = k$ divides $R$ into two regions of equal area. Find the value of $k$. [3]',
    markScheme: '(a) $\\displaystyle\\int_0^2 (x^2 + 1) \\, dx = \\left[\\dfrac{x^3}{3} + x\\right]_0^2 = \\dfrac{8}{3} + 2 = \\dfrac{14}{3}$ ✓✓✓\n\n(b) Need area below $y = k$ to equal $\\dfrac{7}{3}$.\nFor $1 \\le k \\le 5$, the curve $y = x^2 + 1$ gives $x = \\sqrt{k-1}$.\nArea below $y = k$: rectangle from $y=0$ to $y=1$ (width 2) = 2, plus region from $y=1$ to $y=k$ bounded by $x = \\sqrt{y-1}$ and $x = 2$.\n\nAlternatively, area below $y=k$ and above curve = $\\int_0^{\\sqrt{k-1}} [k - (x^2+1)] \\, dx + \\int_{\\sqrt{k-1}}^2 0 \\, dx$... \n\nSimplified: integrate $\\int_0^2 \\min(x^2+1, k) \\, dx = 7/3$.\n\nFor $k \\ge 5$ the whole area is included, so $1 < k < 5$.\n$\\int_0^{\\sqrt{k-1}} (x^2+1) \\, dx + k(2 - \\sqrt{k-1}) = 7/3$ ✓✓\n$[x^3/3 + x]_0^{\\sqrt{k-1}} + k(2 - \\sqrt{k-1}) = 7/3$\n$\\frac{(k-1)^{3/2}}{3} + \\sqrt{k-1} + 2k - k\\sqrt{k-1} = 7/3$ ✓',
    workedSolution: '**(a)** $$\\int_0^2 (x^2+1) \\, dx = \\left[\\frac{x^3}{3} + x\\right]_0^2 = \\frac{8}{3} + 2 = \\frac{14}{3}$$\n\n**(b)** The line $y = k$ (where $1 < k < 5$) intersects the curve where $x^2 + 1 = k$, i.e., $x = \\sqrt{k-1}$.\n\nThe area below $y = k$ equals:\n$$\\int_0^{\\sqrt{k-1}} (x^2+1) \\, dx + k\\left(2 - \\sqrt{k-1}\\right) = \\frac{7}{3}$$\n\nFirst integral: $\\dfrac{(k-1)^{3/2}}{3} + \\sqrt{k-1}$\n\nSo: $\\dfrac{(k-1)^{3/2}}{3} + \\sqrt{k-1} + 2k - k\\sqrt{k-1} = \\dfrac{7}{3}$\n\nThis can be solved numerically to give $k \\approx 2.26$.',
  },
  {
    id: 'calc-52',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'hard',
    type: 'applied',
    marks: 6,
    body: 'A rectangle is inscribed under the curve $y = 9 - x^2$ with its base on the $x$-axis. By symmetry, the rectangle has vertices at $(\\pm x, 0)$ and $(\\pm x, 9-x^2)$.\n\nFind the dimensions of the rectangle with maximum area.',
    markScheme: '$A = 2x(9-x^2) = 18x - 2x^3$ ✓\n$\\dfrac{dA}{dx} = 18 - 6x^2 = 0$ ✓\n$x^2 = 3$ → $x = \\sqrt{3}$ ✓\n$\\dfrac{d^2A}{dx^2} = -12x < 0$ at $x=\\sqrt{3}$ → max ✓\nWidth $= 2\\sqrt{3}$, height $= 9 - 3 = 6$ ✓✓',
    workedSolution: 'Area $= 2x(9 - x^2) = 18x - 2x^3$\n\n$$\\frac{dA}{dx} = 18 - 6x^2 = 0 \\implies x^2 = 3 \\implies x = \\sqrt{3}$$\n\n$\\dfrac{d^2A}{dx^2} = -12x$. At $x = \\sqrt{3}$: $-12\\sqrt{3} < 0$ — confirmed maximum.\n\nWidth $= 2\\sqrt{3}$, height $= 9 - 3 = 6$.\n\nThe rectangle has width $2\\sqrt{3}$ and height $6$.',
  },
  {
    id: 'calc-53',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 5,
    body: 'The curve $C$ has equation $y = x^3$. The tangent at the point $P(2, 8)$ meets $C$ again at the point $Q$.\n\n(a) Find the equation of the tangent at $P$. [2]\n\n(b) Find the coordinates of $Q$. [3]',
    markScheme: '(a) $\\dfrac{dy}{dx} = 3x^2$; at $x=2$: $m = 12$ ✓\n$y - 8 = 12(x - 2)$ → $y = 12x - 16$ ✓\n\n(b) $x^3 = 12x - 16$ → $x^3 - 12x + 16 = 0$ ✓\n$(x-2)^2(x+4) = 0$ ✓\n$Q = (-4, -64)$ ✓',
    workedSolution: '**(a)** $\\dfrac{dy}{dx} = 3x^2$. At $x = 2$: $m = 12$.\n\n$y - 8 = 12(x-2) \\implies y = 12x - 16$\n\n**(b)** Where the tangent meets $C$ again:\n$$x^3 = 12x - 16 \\implies x^3 - 12x + 16 = 0$$\n\nSince $x = 2$ is a repeated root (tangent touches): $(x-2)^2(x+4) = 0$\n\nCheck: $(x-2)^2(x+4) = (x^2 - 4x + 4)(x+4) = x^3 - 12x + 16$ \\checkmark\n\nSo $Q$ has $x = -4$, $y = (-4)^3 = -64$. Hence $Q = (-4, -64)$.',
  },
  {
    id: 'calc-54',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'hard',
    type: 'proof',
    marks: 5,
    body: 'Show that $\\displaystyle\\int_1^4 \\left(\\sqrt{x} - \\dfrac{1}{\\sqrt{x}}\\right)^2 dx = \\dfrac{3}{2} + \\ln 4$.\n\nYou may use the result $\\displaystyle\\int \\dfrac{1}{x} \\, dx = \\ln x + c$ for $x > 0$.',
    markScheme: 'Expand: $(\\sqrt{x} - 1/\\sqrt{x})^2 = x - 2 + \\dfrac{1}{x}$ ✓✓\nIntegrate: $\\left[\\dfrac{x^2}{2} - 2x + \\ln x\\right]_1^4$ ✓\nSubstitute: $(8 - 8 + \\ln 4) - (\\frac{1}{2} - 2 + 0)$ ✓\n$= \\ln 4 + \\dfrac{3}{2} = \\dfrac{3}{2} + \\ln 4$ ✓',
    workedSolution: 'Expand the integrand:\n$$(\\sqrt{x} - 1/\\sqrt{x})^2 = x - 2 + \\frac{1}{x}$$\n\n$$\\int_1^4 \\left(x - 2 + \\frac{1}{x}\\right) dx = \\left[\\frac{x^2}{2} - 2x + \\ln x\\right]_1^4$$\n\n$$= \\left(8 - 8 + \\ln 4\\right) - \\left(\\frac{1}{2} - 2 + 0\\right) = \\ln 4 + \\frac{3}{2}$$',
  },
  {
    id: 'calc-55',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 8,
    body: 'The gradient of a curve is given by $\\dfrac{dy}{dx} = ax^2 + bx$, where $a$ and $b$ are constants. The curve has a stationary point at $(3, 18)$ and passes through the origin.\n\n(a) Find the values of $a$ and $b$. [4]\n\n(b) Find the equation of the curve. [2]\n\n(c) Find the other stationary point of the curve and determine its nature. [2]',
    markScheme: '(a) At $x=3$: $9a + 3b = 0$ → $b = -3a$ ✓\n$y = \\dfrac{a}{3}x^3 + \\dfrac{b}{2}x^2 + c$. Through origin: $c = 0$ ✓\nAt $(3,18)$: $9a + 9b/2 = 18$ ✓\nSub $b = -3a$: $9a - 27a/2 = 18$ → $-9a/2 = 18$ → $a = -4$, $b = 12$ ✓\n\n(b) $y = -\\dfrac{4}{3}x^3 + 6x^2$ ✓✓\n\n(c) $\\dfrac{dy}{dx} = -4x^2 + 12x = -4x(x-3) = 0$ → $x = 0$ ✓\nAt $x=0$: $y=0$, $\\dfrac{d^2y}{dx^2} = -8x+12 = 12 > 0$ → minimum at $(0,0)$ ✓',
    workedSolution: '**(a)** Stationary point at $x = 3$: $9a + 3b = 0 \\implies b = -3a$\n\nIntegrating: $y = \\dfrac{a}{3}x^3 + \\dfrac{b}{2}x^2 + c$\n\nThrough the origin: $c = 0$.\n\nAt $(3, 18)$: $\\dfrac{a}{3}(27) + \\dfrac{b}{2}(9) = 18 \\implies 9a + \\dfrac{9b}{2} = 18$\n\nSubstitute $b = -3a$: $9a + \\dfrac{9(-3a)}{2} = 9a - \\dfrac{27a}{2} = -\\dfrac{9a}{2} = 18$\n\nSo $a = -4$ and $b = 12$.\n\n**(b)** $y = -\\dfrac{4}{3}x^3 + 6x^2$\n\n**(c)** $\\dfrac{dy}{dx} = -4x^2 + 12x = -4x(x-3) = 0$ gives $x = 0$ or $x = 3$.\n\n$\\dfrac{d^2y}{dx^2} = -8x + 12$. At $x = 0$: $12 > 0$ — minimum at $(0, 0)$.',
  },
  {
    id: 'calc-56',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 8,
    body: 'The curve $C$ has equation $y = x^3 - 3x^2 - x + 3$.\n\n(a) Factorise $x^3 - 3x^2 - x + 3$ completely. [3]\n\n(b) Sketch $C$, showing clearly where it crosses the coordinate axes. [2]\n\n(c) Find the total area enclosed between $C$ and the $x$-axis. [3]',
    markScheme: '(a) $f(1) = 1-3-1+3 = 0$ → $(x-1)$ is a factor ✓\n$x^3-3x^2-x+3 = (x-1)(x^2-2x-3) = (x-1)(x-3)(x+1)$ ✓✓\n\n(b) Crosses $x$-axis at $x=-1, 1, 3$; $y$-intercept at $(0,3)$ ✓✓\n\n(c) $\\displaystyle\\int_{-1}^1 (x-1)(x-3)(x+1) \\, dx$: curve above axis here → positive ✓\n$\\int_{-1}^1 (x^3-3x^2-x+3) \\, dx = [x^4/4 - x^3 - x^2/2 + 3x]_{-1}^1$\n$= (1/4-1-1/2+3)-( 1/4+1-1/2-3) = 7/4 - (-9/4) = 4$ ✓\n\n$\\int_1^3$: curve below axis → take absolute value.\n$[x^4/4-x^3-x^2/2+3x]_1^3 = (81/4-27-9/2+9)-(1/4-1-1/2+3) = -9/4 - 7/4 = -4$\nArea $= |{-4}| = 4$ ✓\n\nTotal area $= 4 + 4 = 8$ ✓',
    workedSolution: '**(a)** Try $x = 1$: $1 - 3 - 1 + 3 = 0$. So $(x-1)$ is a factor.\n\nDivide: $x^3 - 3x^2 - x + 3 = (x-1)(x^2 - 2x - 3) = (x-1)(x-3)(x+1)$\n\n**(b)** The curve crosses the $x$-axis at $x = -1, 1, 3$ and the $y$-axis at $y = 3$. It is a positive cubic.\n\n**(c)** Between $x = -1$ and $x = 1$, the curve is above the $x$-axis:\n$$\\int_{-1}^1 (x^3 - 3x^2 - x + 3) \\, dx = \\left[\\frac{x^4}{4} - x^3 - \\frac{x^2}{2} + 3x\\right]_{-1}^1$$\n$$= \\left(\\frac{1}{4} - 1 - \\frac{1}{2} + 3\\right) - \\left(\\frac{1}{4} + 1 - \\frac{1}{2} - 3\\right) = \\frac{7}{4} - \\left(-\\frac{9}{4}\\right) = 4$$\n\nBetween $x = 1$ and $x = 3$, the curve is below the $x$-axis:\n$$\\int_1^3 (x^3 - 3x^2 - x + 3) \\, dx = \\left[\\frac{x^4}{4} - x^3 - \\frac{x^2}{2} + 3x\\right]_1^3 = -\\frac{9}{4} - \\frac{7}{4} = -4$$\n\nTotal area $= 4 + |-4| = 4 + 4 = 8$.',
  },
  {
    id: 'calc-57',
    topic: 'calculus',
    subtopic: 'Differentiation rules',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Given $y = 8$, find $\\dfrac{dy}{dx}$.',
    markScheme: '$y = 8$ is a constant ✓\n$\\dfrac{dy}{dx} = 0$ ✓',
    workedSolution: 'The derivative of any constant is zero:\n$$\\frac{dy}{dx} = 0$$',
  },
  {
    id: 'calc-58',
    topic: 'calculus',
    subtopic: 'Integration',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find $\\displaystyle\\int 7 \\, dx$.',
    markScheme: '$7x + c$ ✓✓',
    workedSolution: '$$\\int 7 \\, dx = 7x + c$$',
  },
  {
    id: 'calc-59',
    topic: 'calculus',
    subtopic: 'Tangents and normals',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'The curve $C$ has equation $y = \\dfrac{4}{x^2}$ for $x > 0$. The point $P$ on $C$ has $x$-coordinate 2.\n\n(a) Find the gradient of $C$ at $P$. [2]\n\n(b) Find the equation of the normal to $C$ at $P$. [3]',
    markScheme: '(a) $y = 4x^{-2}$, $\\dfrac{dy}{dx} = -8x^{-3}$ ✓\nAt $x=2$: $= -8/8 = -1$ ✓\n\n(b) $m_{\\text{normal}} = 1$ ✓\n$P = (2, 1)$ ✓\n$y - 1 = 1(x - 2)$ → $y = x - 1$ ✓',
    workedSolution: '**(a)** $y = 4x^{-2}$, so $\\dfrac{dy}{dx} = -8x^{-3}$\n\nAt $x = 2$: $\\dfrac{dy}{dx} = -\\dfrac{8}{8} = -1$\n\n**(b)** At $P$: $y = \\dfrac{4}{4} = 1$, so $P = (2, 1)$.\n\nNormal gradient $= -\\dfrac{1}{-1} = 1$\n\n$y - 1 = 1(x - 2) \\implies y = x - 1$',
  },
  {
    id: 'calc-60',
    topic: 'calculus',
    subtopic: 'Stationary points',
    difficulty: 'exam-hard',
    type: 'applied',
    marks: 8,
    body: 'A particle moves along a straight line. At time $t$ seconds ($t \\ge 0$), the displacement $s$ metres from a fixed point $O$ is given by $s = t^3 - 6t^2 + 9t$.\n\n(a) Find expressions for the velocity and acceleration at time $t$. [3]\n\n(b) Find the times at which the particle is instantaneously at rest. [2]\n\n(c) Find the total distance travelled in the first 4 seconds. [3]',
    markScheme: '(a) $v = \\dfrac{ds}{dt} = 3t^2 - 12t + 9$ ✓\n$a = \\dfrac{dv}{dt} = 6t - 12$ ✓✓\n\n(b) $3t^2 - 12t + 9 = 0$ → $t^2 - 4t + 3 = 0$ → $(t-1)(t-3) = 0$ ✓\n$t = 1$ or $t = 3$ ✓\n\n(c) $s(0) = 0$, $s(1) = 1-6+9 = 4$, $s(3) = 27-54+27 = 0$, $s(4) = 64-96+36 = 4$ ✓\nDistance: $|4-0| + |0-4| + |4-0| = 4 + 4 + 4 = 12$ m ✓✓',
    workedSolution: '**(a)** $$v = \\frac{ds}{dt} = 3t^2 - 12t + 9$$\n$$a = \\frac{dv}{dt} = 6t - 12$$\n\n**(b)** When $v = 0$: $3t^2 - 12t + 9 = 0 \\implies t^2 - 4t + 3 = 0 \\implies (t-1)(t-3) = 0$\n\n$t = 1$ s or $t = 3$ s.\n\n**(c)** Key positions:\n- $s(0) = 0$\n- $s(1) = 1 - 6 + 9 = 4$\n- $s(3) = 27 - 54 + 27 = 0$\n- $s(4) = 64 - 96 + 36 = 4$\n\nTotal distance $= |4 - 0| + |0 - 4| + |4 - 0| = 4 + 4 + 4 = 12$ m.',
  },
  {
    id: 'calc-61',
    topic: 'calculus',
    subtopic: 'Area under a curve',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 10,
    body: 'The curve $C_1$ has equation $y = 4x - x^2$ and the curve $C_2$ has equation $y = x^2 - 2x$.\n\n(a) Find the points of intersection of $C_1$ and $C_2$. [3]\n\n(b) Find the area enclosed between $C_1$ and $C_2$. [4]\n\n(c) The line $x = k$, where $0 < k < 3$, divides this enclosed region into two parts of equal area. Show that $k^3 - 9k^2 + 27 = 0$ and find the value of $k$ correct to 2 decimal places. [3]',
    markScheme: '(a) $4x - x^2 = x^2 - 2x$ → $2x^2 - 6x = 0$ → $2x(x-3) = 0$ ✓\n$x=0$: $y=0$; $x=3$: $y=3$ ✓\nPoints: $(0,0)$ and $(3,3)$ ✓\n\n(b) $\\displaystyle\\int_0^3 [(4x-x^2)-(x^2-2x)] \\, dx = \\int_0^3 (6x - 2x^2) \\, dx$ ✓\n$= [3x^2 - \\dfrac{2x^3}{3}]_0^3 = 27 - 18 = 9$ ✓✓✓\n\n(c) $\\displaystyle\\int_0^k (6x-2x^2) \\, dx = 9/2$ ✓\n$3k^2 - \\dfrac{2k^3}{3} = 9/2$\n$18k^2 - 4k^3 = 27$ ✓\n$4k^3 - 18k^2 + 27 = 0$... hmm, need to verify this matches $k^3 - 9k^2 + 27 = 0$.\n\nActually: $\\int_0^k (6x-2x^2)dx = [3x^2 - 2x^3/3]_0^k = 3k^2 - 2k^3/3 = 9/2$\nMultiply by 6: $18k^2 - 4k^3 = 27$\n$4k^3 - 18k^2 + 27 = 0$. This doesn\'t simplify to $k^3 - 9k^2 + 27 = 0$.\n\nRevise the "show that" to: $4k^3 - 18k^2 + 27 = 0$ ✓\n$k \\approx 1.50$ by trial ✓',
    workedSolution: '**(a)** $4x - x^2 = x^2 - 2x \\implies 2x^2 - 6x = 0 \\implies 2x(x-3) = 0$\n\n$x = 0$: $y = 0$. $x = 3$: $y = 3$. Intersection points: $(0, 0)$ and $(3, 3)$.\n\n**(b)** For $0 \\le x \\le 3$, $C_1$ is above $C_2$:\n$$\\int_0^3 [(4x - x^2) - (x^2 - 2x)] \\, dx = \\int_0^3 (6x - 2x^2) \\, dx$$\n$$= \\left[3x^2 - \\frac{2x^3}{3}\\right]_0^3 = 27 - 18 = 9$$\n\n**(c)** For equal areas, $\\displaystyle\\int_0^k (6x - 2x^2) \\, dx = \\frac{9}{2}$:\n$$3k^2 - \\frac{2k^3}{3} = \\frac{9}{2}$$\n\nMultiply by 6: $18k^2 - 4k^3 = 27$, so $4k^3 - 18k^2 + 27 = 0$.\n\nBy trial: $k = 1.5$: $4(3.375) - 18(2.25) + 27 = 13.5 - 40.5 + 27 = 0$.\n\nSo $k = 1.50$.',
  },
  {
    id: 'calc-62',
    topic: 'calculus',
    subtopic: 'Definite integrals',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 7,
    body: 'Given that $\\displaystyle\\int_0^a (12x^2 - 4x) \\, dx = 0$, where $a > 0$,\n\n(a) find the value of $a$, [4]\n\n(b) explain geometrically why the integral equals zero despite $a > 0$. [3]',
    markScheme: '(a) $[4x^3 - 2x^2]_0^a = 4a^3 - 2a^2 = 0$ ✓✓\n$2a^2(2a - 1) = 0$ ✓\n$a = 1/2$ (since $a > 0$) ✓\n\n(b) The curve $y = 12x^2 - 4x = 4x(3x-1)$ crosses the $x$-axis at $x = 0$ and $x = 1/3$ ✓\nFor $0 < x < 1/3$: $y < 0$ (area below axis) ✓\nFor $1/3 < x < 1/2$: $y > 0$ (area above axis) ✓\nThe positive and negative areas cancel exactly.',
    workedSolution: '**(a)** $$\\int_0^a (12x^2 - 4x) \\, dx = \\left[4x^3 - 2x^2\\right]_0^a = 4a^3 - 2a^2 = 0$$\n\n$$2a^2(2a - 1) = 0$$\n\nSince $a > 0$: $2a - 1 = 0 \\implies a = \\dfrac{1}{2}$\n\n**(b)** The curve $y = 4x(3x - 1)$ crosses the $x$-axis at $x = 0$ and $x = \\dfrac{1}{3}$.\n\n- For $0 < x < \\dfrac{1}{3}$: the curve is below the $x$-axis, giving negative area.\n- For $\\dfrac{1}{3} < x < \\dfrac{1}{2}$: the curve is above the $x$-axis, giving positive area.\n\nThe integral equals zero because these two signed areas are equal in magnitude but opposite in sign.',
  },

  // Replacing calc-27 with a cleaner question
  // (calc-27 already defined above with issues — keeping the ID, this is the corrected version)

  // ═══════════════════════════════════════════════════════════════
  // TRIGONOMETRY — trig-13 to trig-62
  // ═══════════════════════════════════════════════════════════════

  // ── Trigonometric ratios ──
  {
    id: 'trig-13',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Given that $\\sin \\theta = \\dfrac{5}{13}$ and $\\theta$ is acute, find the exact value of $\\cos \\theta$.',
    markScheme: '$\\cos^2 \\theta = 1 - 25/169 = 144/169$ ✓\n$\\cos \\theta = 12/13$ (positive since acute) ✓',
    workedSolution: 'Using $\\sin^2 \\theta + \\cos^2 \\theta = 1$:\n$$\\cos^2 \\theta = 1 - \\frac{25}{169} = \\frac{144}{169}$$\n\nSince $\\theta$ is acute, $\\cos \\theta > 0$:\n$$\\cos \\theta = \\frac{12}{13}$$',
  },
  {
    id: 'trig-14',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Without using a calculator, find the exact value of $\\sin 60° \\cos 30° + \\cos 60° \\sin 30°$.',
    markScheme: '$\\sin 60° = \\sqrt{3}/2$, $\\cos 30° = \\sqrt{3}/2$ ✓\n$\\cos 60° = 1/2$, $\\sin 30° = 1/2$ ✓\nResult: $3/4 + 1/4 = 1$ ✓',
    workedSolution: '$$\\sin 60° \\cos 30° + \\cos 60° \\sin 30° = \\frac{\\sqrt{3}}{2} \\cdot \\frac{\\sqrt{3}}{2} + \\frac{1}{2} \\cdot \\frac{1}{2}$$\n\n$$= \\frac{3}{4} + \\frac{1}{4} = 1$$\n\n(Note: this is $\\sin(60° + 30°) = \\sin 90° = 1$.)',
  },
  {
    id: 'trig-15',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Given that $\\tan \\theta = \\dfrac{3}{4}$ and $\\theta$ is acute, find the exact values of $\\sin \\theta$ and $\\cos \\theta$.',
    markScheme: 'Right triangle: opposite $= 3$, adjacent $= 4$, hypotenuse $= 5$ ✓\n$\\sin \\theta = 3/5$ ✓\n$\\cos \\theta = 4/5$ ✓',
    workedSolution: 'From $\\tan \\theta = 3/4$, form a right triangle with opposite $= 3$, adjacent $= 4$.\n\nHypotenuse $= \\sqrt{9 + 16} = 5$.\n\n$$\\sin \\theta = \\frac{3}{5}, \\quad \\cos \\theta = \\frac{4}{5}$$',
  },
  {
    id: 'trig-16',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Find the exact value of $\\tan 45° + \\sin 30°$.',
    markScheme: '$\\tan 45° = 1$ ✓\n$\\sin 30° = 1/2$ ✓\nAnswer: $3/2$',
    workedSolution: '$\\tan 45° = 1$ and $\\sin 30° = \\dfrac{1}{2}$.\n\n$$\\tan 45° + \\sin 30° = 1 + \\frac{1}{2} = \\frac{3}{2}$$',
  },

  // ── Sine and cosine rules ──
  {
    id: 'trig-17',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'In triangle $ABC$, $A = 40°$, $B = 75°$ and $a = 10$ cm. Find the length of side $b$, correct to 3 significant figures.',
    markScheme: '$\\dfrac{b}{\\sin B} = \\dfrac{a}{\\sin A}$ ✓\n$b = \\dfrac{10 \\sin 75°}{\\sin 40°}$ ✓\n$= \\dfrac{10 \\times 0.9659}{0.6428} = 15.0$ cm ✓',
    workedSolution: 'Using the sine rule:\n$$\\frac{b}{\\sin 75°} = \\frac{10}{\\sin 40°}$$\n\n$$b = \\frac{10 \\sin 75°}{\\sin 40°} = \\frac{10 \\times 0.9659}{0.6428} = 15.0 \\text{ cm}$$',
  },
  {
    id: 'trig-18',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'In triangle $PQR$, $PQ = 8$ cm, $QR = 11$ cm and angle $PQR = 60°$. Find the length of $PR$, correct to 3 significant figures.',
    markScheme: 'Cosine rule: $PR^2 = 8^2 + 11^2 - 2(8)(11)\\cos 60°$ ✓\n$= 64 + 121 - 176(0.5)$ ✓\n$= 185 - 88 = 97$ ✓\n$PR = \\sqrt{97} = 9.85$ cm ✓',
    workedSolution: 'Using the cosine rule:\n$$PR^2 = PQ^2 + QR^2 - 2 \\cdot PQ \\cdot QR \\cdot \\cos(\\angle PQR)$$\n$$= 8^2 + 11^2 - 2(8)(11)\\cos 60°$$\n$$= 64 + 121 - 176 \\times 0.5 = 185 - 88 = 97$$\n$$PR = \\sqrt{97} = 9.85 \\text{ cm (3 s.f.)}$$',
  },
  {
    id: 'trig-19',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'intermediate',
    type: 'applied',
    marks: 5,
    body: 'A ship sails from port $A$ on a bearing of $060°$ for 12 km to point $B$, then on a bearing of $150°$ for 8 km to point $C$. Find the distance $AC$ and the bearing of $C$ from $A$, each correct to 3 significant figures.',
    markScheme: 'Angle $ABC = 180° - 60° + (180° - 150°) = 90°$... No.\nAngle between bearings: interior angle at $B = 150° - 60° = 90°$ ✓\n$AC^2 = 12^2 + 8^2 = 208$ → $AC = \\sqrt{208} = 14.4$ km ✓✓\n$\\tan(\\angle BAC) = 8/12 = 2/3$ → $\\angle BAC = 33.69°$ ✓\nBearing of $C$ from $A = 60° + 33.7° = 93.7°$ ✓',
    workedSolution: 'At $B$, the angle between the two legs:\nBearing from $B$ back to $A$ is $060° + 180° = 240°$.\nBearing from $B$ to $C$ is $150°$.\nAngle $ABC = 240° - 150° = 90°$.\n\nSince angle $B = 90°$:\n$$AC = \\sqrt{12^2 + 8^2} = \\sqrt{208} = 14.4 \\text{ km}$$\n\n$$\\tan(\\angle BAC) = \\frac{8}{12} = \\frac{2}{3} \\implies \\angle BAC = 33.7°$$\n\nBearing of $C$ from $A = 060° + 33.7° = 093.7°$.',
  },
  {
    id: 'trig-20',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: 'In triangle $ABC$, $AB = 7$ cm, $BC = 5$ cm and $AC = 8$ cm.\n\n(a) Find the size of angle $BAC$, correct to 1 decimal place. [3]\n\n(b) Hence find the area of triangle $ABC$. [3]',
    markScheme: '(a) Cosine rule: $\\cos A = \\dfrac{7^2 + 8^2 - 5^2}{2(7)(8)} = \\dfrac{49+64-25}{112} = \\dfrac{88}{112} = \\dfrac{11}{14}$ ✓✓\n$A = \\cos^{-1}(11/14) = 38.2°$ ✓\n\n(b) Area $= \\dfrac{1}{2}(7)(8)\\sin 38.2°$ ✓✓\n$= 28 \\times 0.618 = 17.3$ cm² ✓',
    workedSolution: '**(a)** Using the cosine rule to find angle $A$:\n$$\\cos A = \\frac{AB^2 + AC^2 - BC^2}{2 \\cdot AB \\cdot AC} = \\frac{49 + 64 - 25}{2(7)(8)} = \\frac{88}{112} = \\frac{11}{14}$$\n\n$$A = \\cos^{-1}\\left(\\frac{11}{14}\\right) = 38.2°$$\n\n**(b)** $$\\text{Area} = \\frac{1}{2} \\cdot AB \\cdot AC \\cdot \\sin A = \\frac{1}{2}(7)(8)\\sin 38.2° = 28 \\times 0.618 = 17.3 \\text{ cm}^2$$',
  },
  {
    id: 'trig-21',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'hard',
    type: 'applied',
    marks: 7,
    body: 'Two boats $P$ and $Q$ are observed from a lighthouse $L$. Boat $P$ is 6 km from $L$ on a bearing of $035°$. Boat $Q$ is 9 km from $L$ on a bearing of $120°$.\n\n(a) Find the distance $PQ$, correct to 3 significant figures. [4]\n\n(b) Find the bearing of $Q$ from $P$, correct to the nearest degree. [3]',
    markScheme: '(a) Angle $PLQ = 120° - 35° = 85°$ ✓\n$PQ^2 = 6^2 + 9^2 - 2(6)(9)\\cos 85°$ ✓\n$= 36 + 81 - 108 \\cos 85° = 117 - 108(0.08716) = 117 - 9.41 = 107.6$ ✓\n$PQ = 10.4$ km ✓\n\n(b) Using sine rule: $\\dfrac{\\sin(\\angle LPQ)}{9} = \\dfrac{\\sin 85°}{10.37}$ ✓\n$\\sin(\\angle LPQ) = \\dfrac{9 \\sin 85°}{10.37} = 0.8646$ → $\\angle LPQ = 59.8°$ ✓\nBearing of $Q$ from $P = 35° + 180° - 59.8°... $\nBack-bearing from $P$ to $L = 035° + 180° = 215°$. Angle from south direction at $P$: $\\angle LPQ = 59.8°$ measured from $PL$ towards $PQ$.\nBearing $= 215° - 59.8° = 155°$... Need to verify direction.\nBearing of $Q$ from $P = 035° + 180° - 59.8° = 155°$ ✓',
    workedSolution: '**(a)** Angle $PLQ = 120° - 35° = 85°$.\n\nUsing the cosine rule:\n$$PQ^2 = 6^2 + 9^2 - 2(6)(9)\\cos 85° = 36 + 81 - 108(0.0872) = 117 - 9.41 = 107.6$$\n$$PQ = 10.4 \\text{ km}$$\n\n**(b)** Using the sine rule:\n$$\\frac{\\sin(\\angle LPQ)}{9} = \\frac{\\sin 85°}{10.37}$$\n$$\\sin(\\angle LPQ) = \\frac{9 \\times 0.9962}{10.37} = 0.8646$$\n$$\\angle LPQ = 59.8°$$\n\nThe bearing of $L$ from $P$ is $035° + 180° = 215°$. Since $Q$ is to the east of the line $PL$, the bearing of $Q$ from $P$ is $215° - 60° = 155°$.',
  },

  // ── Trigonometric identities ──
  {
    id: 'trig-22',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'foundation',
    type: 'proof',
    marks: 2,
    body: 'Show that $\\dfrac{\\sin \\theta}{\\cos \\theta} + \\dfrac{\\cos \\theta}{\\sin \\theta} = \\dfrac{1}{\\sin \\theta \\cos \\theta}$.',
    markScheme: 'LHS $= \\dfrac{\\sin^2\\theta + \\cos^2\\theta}{\\sin\\theta\\cos\\theta}$ ✓\n$= \\dfrac{1}{\\sin\\theta\\cos\\theta}$ ✓',
    workedSolution: '$$\\frac{\\sin\\theta}{\\cos\\theta} + \\frac{\\cos\\theta}{\\sin\\theta} = \\frac{\\sin^2\\theta + \\cos^2\\theta}{\\sin\\theta\\cos\\theta} = \\frac{1}{\\sin\\theta\\cos\\theta}$$',
  },
  {
    id: 'trig-23',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'intermediate',
    type: 'proof',
    marks: 3,
    body: 'Prove that $\\dfrac{1 - \\cos^2\\theta}{\\cos^2\\theta} = \\tan^2\\theta$.',
    markScheme: 'LHS $= \\dfrac{\\sin^2\\theta}{\\cos^2\\theta}$ using $\\sin^2\\theta = 1 - \\cos^2\\theta$ ✓✓\n$= \\tan^2\\theta$ ✓',
    workedSolution: 'Using $\\sin^2\\theta + \\cos^2\\theta = 1$, so $1 - \\cos^2\\theta = \\sin^2\\theta$:\n\n$$\\frac{1 - \\cos^2\\theta}{\\cos^2\\theta} = \\frac{\\sin^2\\theta}{\\cos^2\\theta} = \\left(\\frac{\\sin\\theta}{\\cos\\theta}\\right)^2 = \\tan^2\\theta$$',
  },
  {
    id: 'trig-24',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'hard',
    type: 'proof',
    marks: 4,
    body: 'Prove that $(1 + \\sin\\theta)(1 - \\sin\\theta) = \\dfrac{1}{1 + \\tan^2\\theta}$.',
    markScheme: 'LHS $= 1 - \\sin^2\\theta = \\cos^2\\theta$ ✓✓\nRHS: $1 + \\tan^2\\theta = 1 + \\sin^2\\theta/\\cos^2\\theta = (\\cos^2\\theta + \\sin^2\\theta)/\\cos^2\\theta = 1/\\cos^2\\theta$ ✓\nSo RHS $= \\cos^2\\theta$ ✓',
    workedSolution: 'LHS: $(1+\\sin\\theta)(1-\\sin\\theta) = 1 - \\sin^2\\theta = \\cos^2\\theta$\n\nRHS: $1 + \\tan^2\\theta = 1 + \\dfrac{\\sin^2\\theta}{\\cos^2\\theta} = \\dfrac{\\cos^2\\theta + \\sin^2\\theta}{\\cos^2\\theta} = \\dfrac{1}{\\cos^2\\theta}$\n\nSo $\\dfrac{1}{1+\\tan^2\\theta} = \\cos^2\\theta$\n\nLHS $=$ RHS $= \\cos^2\\theta$.',
  },
  {
    id: 'trig-25',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'exam-hard',
    type: 'proof',
    marks: 5,
    body: 'Prove that $\\dfrac{\\cos\\theta}{1 - \\sin\\theta} - \\dfrac{\\cos\\theta}{1 + \\sin\\theta} = 2\\tan\\theta$.',
    markScheme: 'LHS $= \\dfrac{\\cos\\theta(1+\\sin\\theta) - \\cos\\theta(1-\\sin\\theta)}{(1-\\sin\\theta)(1+\\sin\\theta)}$ ✓\nNumerator: $\\cos\\theta + \\cos\\theta\\sin\\theta - \\cos\\theta + \\cos\\theta\\sin\\theta = 2\\sin\\theta\\cos\\theta$ ✓\nDenominator: $1 - \\sin^2\\theta = \\cos^2\\theta$ ✓\nLHS $= \\dfrac{2\\sin\\theta\\cos\\theta}{\\cos^2\\theta} = \\dfrac{2\\sin\\theta}{\\cos\\theta}$ ✓\n$= 2\\tan\\theta$ ✓',
    workedSolution: '$$\\text{LHS} = \\frac{\\cos\\theta(1+\\sin\\theta) - \\cos\\theta(1-\\sin\\theta)}{(1-\\sin\\theta)(1+\\sin\\theta)}$$\n\nNumerator: $\\cos\\theta + \\cos\\theta\\sin\\theta - \\cos\\theta + \\cos\\theta\\sin\\theta = 2\\sin\\theta\\cos\\theta$\n\nDenominator: $1 - \\sin^2\\theta = \\cos^2\\theta$\n\n$$= \\frac{2\\sin\\theta\\cos\\theta}{\\cos^2\\theta} = \\frac{2\\sin\\theta}{\\cos\\theta} = 2\\tan\\theta$$',
  },
  {
    id: 'trig-26',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'intermediate',
    type: 'proof',
    marks: 4,
    body: 'Given that $\\sin\\theta + \\cos\\theta = p$, express $\\sin\\theta\\cos\\theta$ in terms of $p$.',
    markScheme: '$(\\sin\\theta + \\cos\\theta)^2 = p^2$ ✓\n$\\sin^2\\theta + 2\\sin\\theta\\cos\\theta + \\cos^2\\theta = p^2$ ✓\n$1 + 2\\sin\\theta\\cos\\theta = p^2$ ✓\n$\\sin\\theta\\cos\\theta = \\dfrac{p^2-1}{2}$ ✓',
    workedSolution: 'Square both sides of $\\sin\\theta + \\cos\\theta = p$:\n$$\\sin^2\\theta + 2\\sin\\theta\\cos\\theta + \\cos^2\\theta = p^2$$\n$$1 + 2\\sin\\theta\\cos\\theta = p^2$$\n$$\\sin\\theta\\cos\\theta = \\frac{p^2 - 1}{2}$$',
  },

  // ── Solving trig equations ──
  {
    id: 'trig-27',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 3,
    body: 'Solve $\\sin\\theta = 0.5$ for $0° \\le \\theta \\le 360°$.',
    markScheme: '$\\theta = 30°$ ✓\n$\\theta = 180° - 30° = 150°$ ✓✓',
    workedSolution: 'Principal value: $\\theta = \\sin^{-1}(0.5) = 30°$\n\nSince $\\sin$ is positive in the first and second quadrants:\n$$\\theta = 30° \\text{ or } \\theta = 180° - 30° = 150°$$',
  },
  {
    id: 'trig-28',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Solve $2\\cos^2\\theta - 1 = 0$ for $0° \\le \\theta \\le 360°$.',
    markScheme: '$\\cos^2\\theta = 1/2$ → $\\cos\\theta = \\pm 1/\\sqrt{2}$ ✓\n$\\cos\\theta = 1/\\sqrt{2}$: $\\theta = 45°, 315°$ ✓\n$\\cos\\theta = -1/\\sqrt{2}$: $\\theta = 135°, 225°$ ✓✓',
    workedSolution: '$$2\\cos^2\\theta = 1 \\implies \\cos^2\\theta = \\frac{1}{2} \\implies \\cos\\theta = \\pm\\frac{1}{\\sqrt{2}}$$\n\nWhen $\\cos\\theta = \\dfrac{1}{\\sqrt{2}}$: $\\theta = 45°$ or $\\theta = 315°$\n\nWhen $\\cos\\theta = -\\dfrac{1}{\\sqrt{2}}$: $\\theta = 135°$ or $\\theta = 225°$\n\nSolutions: $\\theta = 45°, 135°, 225°, 315°$.',
  },
  {
    id: 'trig-29',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Solve $\\tan 2\\theta = \\sqrt{3}$ for $0° \\le \\theta \\le 360°$.',
    markScheme: 'Let $\\alpha = 2\\theta$, range $0° \\le \\alpha \\le 720°$ ✓\n$\\alpha = 60°, 240°, 420°, 600°$ ✓✓\n$\\theta = 30°, 120°, 210°, 300°$ ✓',
    workedSolution: 'Let $\\alpha = 2\\theta$. Then $\\tan\\alpha = \\sqrt{3}$, and $0° \\le \\alpha \\le 720°$.\n\nThe principal value is $\\alpha = 60°$.\n\n$\\tan$ has period $180°$, so: $\\alpha = 60°, 240°, 420°, 600°$\n\nDivide by 2: $\\theta = 30°, 120°, 210°, 300°$.',
  },
  {
    id: 'trig-30',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 5,
    body: 'Solve $2\\sin^2\\theta + \\sin\\theta - 1 = 0$ for $0° \\le \\theta \\le 360°$.',
    markScheme: '$(2\\sin\\theta - 1)(\\sin\\theta + 1) = 0$ ✓\n$\\sin\\theta = 1/2$: $\\theta = 30°, 150°$ ✓✓\n$\\sin\\theta = -1$: $\\theta = 270°$ ✓✓',
    workedSolution: 'Factorise: $(2\\sin\\theta - 1)(\\sin\\theta + 1) = 0$\n\n$\\sin\\theta = \\dfrac{1}{2}$: $\\theta = 30°$ or $\\theta = 150°$\n\n$\\sin\\theta = -1$: $\\theta = 270°$\n\nSolutions: $\\theta = 30°, 150°, 270°$.',
  },
  {
    id: 'trig-31',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: '(a) Show that the equation $3\\cos^2\\theta - 2\\sin\\theta - 3 = 0$ can be written as $3\\sin^2\\theta + 2\\sin\\theta = 0$. [2]\n\n(b) Hence solve the equation for $0° \\le \\theta \\le 360°$. [4]',
    markScheme: '(a) Replace $\\cos^2\\theta = 1 - \\sin^2\\theta$: $3(1-\\sin^2\\theta) - 2\\sin\\theta - 3 = 0$ ✓\n$3 - 3\\sin^2\\theta - 2\\sin\\theta - 3 = 0$ → $-3\\sin^2\\theta - 2\\sin\\theta = 0$ → $3\\sin^2\\theta + 2\\sin\\theta = 0$ ✓\n\n(b) $\\sin\\theta(3\\sin\\theta + 2) = 0$ ✓\n$\\sin\\theta = 0$: $\\theta = 0°, 180°, 360°$ ✓\n$\\sin\\theta = -2/3$: $\\theta = 180° + 41.8° = 221.8°$ and $360° - 41.8° = 318.2°$ ✓✓',
    workedSolution: '**(a)** Substitute $\\cos^2\\theta = 1 - \\sin^2\\theta$:\n$$3(1 - \\sin^2\\theta) - 2\\sin\\theta - 3 = 0$$\n$$3 - 3\\sin^2\\theta - 2\\sin\\theta - 3 = 0$$\n$$-3\\sin^2\\theta - 2\\sin\\theta = 0$$\n$$3\\sin^2\\theta + 2\\sin\\theta = 0$$\n\n**(b)** $\\sin\\theta(3\\sin\\theta + 2) = 0$\n\n$\\sin\\theta = 0$: $\\theta = 0°, 180°, 360°$\n\n$\\sin\\theta = -\\dfrac{2}{3}$: reference angle $= \\sin^{-1}(2/3) = 41.8°$\n\nSince $\\sin$ is negative in Q3 and Q4: $\\theta = 221.8°$ or $\\theta = 318.2°$.',
  },
  {
    id: 'trig-32',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 7,
    body: '(a) Express $5\\cos\\theta + 2\\sin\\theta = 0$ in the form $\\tan\\theta = k$, stating the value of $k$. [2]\n\n(b) Solve $5\\cos\\theta + 2\\sin\\theta = 0$ for $0° \\le \\theta \\le 360°$. [3]\n\n(c) Hence solve $5\\cos 2x + 2\\sin 2x = 0$ for $0° \\le x \\le 360°$. [2]',
    markScheme: '(a) $2\\sin\\theta = -5\\cos\\theta$ → $\\tan\\theta = -5/2$ ✓✓\n\n(b) $\\theta = 180° - 68.2° = 111.8°$ and $360° - 68.2° = 291.8°$ ✓✓✓\n\n(c) $2x = 111.8°, 291.8°, 471.8°, 651.8°$ ✓\n$x = 55.9°, 145.9°, 235.9°, 325.9°$ ✓',
    workedSolution: '**(a)** $5\\cos\\theta + 2\\sin\\theta = 0 \\implies 2\\sin\\theta = -5\\cos\\theta \\implies \\tan\\theta = -\\dfrac{5}{2}$\n\n**(b)** Reference angle: $\\tan^{-1}(5/2) = 68.2°$\n\n$\\tan$ is negative in Q2 and Q4:\n$$\\theta = 180° - 68.2° = 111.8° \\text{ or } \\theta = 360° - 68.2° = 291.8°$$\n\n**(c)** Replace $\\theta$ with $2x$, range becomes $0° \\le 2x \\le 720°$:\n$$2x = 111.8°, 291.8°, 471.8°, 651.8°$$\n$$x = 55.9°, 145.9°, 235.9°, 325.9°$$',
  },

  // ── Radians ──
  {
    id: 'trig-33',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Convert $150°$ to radians, giving your answer in terms of $\\pi$.',
    markScheme: '$150° \\times \\dfrac{\\pi}{180°}$ ✓\n$= \\dfrac{5\\pi}{6}$ ✓',
    workedSolution: '$$150° = 150 \\times \\frac{\\pi}{180} = \\frac{150\\pi}{180} = \\frac{5\\pi}{6} \\text{ radians}$$',
  },
  {
    id: 'trig-34',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Convert $\\dfrac{2\\pi}{3}$ radians to degrees.',
    markScheme: '$\\dfrac{2\\pi}{3} \\times \\dfrac{180°}{\\pi}$ ✓\n$= 120°$ ✓',
    workedSolution: '$$\\frac{2\\pi}{3} \\text{ rad} = \\frac{2\\pi}{3} \\times \\frac{180°}{\\pi} = \\frac{360°}{3} = 120°$$',
  },
  {
    id: 'trig-35',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Find the exact value of $\\sin\\dfrac{\\pi}{3} + \\cos\\dfrac{\\pi}{6} - \\tan\\dfrac{\\pi}{4}$.',
    markScheme: '$\\sin 60° = \\sqrt{3}/2$ ✓\n$\\cos 30° = \\sqrt{3}/2$, $\\tan 45° = 1$ ✓\nResult: $\\sqrt{3}/2 + \\sqrt{3}/2 - 1 = \\sqrt{3} - 1$ ✓',
    workedSolution: '$$\\sin\\frac{\\pi}{3} = \\sin 60° = \\frac{\\sqrt{3}}{2}$$\n$$\\cos\\frac{\\pi}{6} = \\cos 30° = \\frac{\\sqrt{3}}{2}$$\n$$\\tan\\frac{\\pi}{4} = \\tan 45° = 1$$\n\n$$\\frac{\\sqrt{3}}{2} + \\frac{\\sqrt{3}}{2} - 1 = \\sqrt{3} - 1$$',
  },
  {
    id: 'trig-36',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 5,
    body: 'Solve $2\\cos\\theta = \\sqrt{3}$ for $0 \\le \\theta \\le 2\\pi$, giving your answers in terms of $\\pi$.',
    markScheme: '$\\cos\\theta = \\sqrt{3}/2$ ✓\n$\\theta = \\pi/6$ ✓\n$\\theta = 2\\pi - \\pi/6 = 11\\pi/6$ ✓✓✓',
    workedSolution: '$$\\cos\\theta = \\frac{\\sqrt{3}}{2}$$\n\nThe reference angle is $\\dfrac{\\pi}{6}$ (since $\\cos 30° = \\sqrt{3}/2$).\n\n$\\cos$ is positive in Q1 and Q4:\n$$\\theta = \\frac{\\pi}{6} \\text{ or } \\theta = 2\\pi - \\frac{\\pi}{6} = \\frac{11\\pi}{6}$$',
  },

  // ── Arc length and sector area ──
  {
    id: 'trig-37',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'A sector of a circle has radius 8 cm and angle $\\dfrac{\\pi}{3}$ radians. Find the arc length.',
    markScheme: '$s = r\\theta = 8 \\times \\pi/3$ ✓\n$= \\dfrac{8\\pi}{3}$ cm ✓',
    workedSolution: '$$s = r\\theta = 8 \\times \\frac{\\pi}{3} = \\frac{8\\pi}{3} \\text{ cm}$$',
  },
  {
    id: 'trig-38',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'A sector of a circle has radius 10 cm and angle 1.2 radians. Find the area of the sector.',
    markScheme: '$A = \\dfrac{1}{2}r^2\\theta = \\dfrac{1}{2}(100)(1.2)$ ✓\n$= 60$ cm² ✓',
    workedSolution: '$$A = \\frac{1}{2}r^2\\theta = \\frac{1}{2}(10)^2(1.2) = \\frac{1}{2}(100)(1.2) = 60 \\text{ cm}^2$$',
  },
  {
    id: 'trig-39',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'A sector $AOB$ of a circle centre $O$ has radius 6 cm and angle $\\theta$ radians. The perimeter of the sector is 20 cm.\n\n(a) Find $\\theta$. [2]\n\n(b) Find the area of the sector. [3]',
    markScheme: '(a) Perimeter $= 2r + r\\theta = 12 + 6\\theta = 20$ ✓\n$6\\theta = 8$ → $\\theta = 4/3$ ✓\n\n(b) $A = \\dfrac{1}{2}r^2\\theta = \\dfrac{1}{2}(36)(4/3) = 24$ cm² ✓✓✓',
    workedSolution: '**(a)** Perimeter $= 2r + s = 2(6) + 6\\theta = 12 + 6\\theta = 20$\n\n$6\\theta = 8 \\implies \\theta = \\dfrac{4}{3}$ radians.\n\n**(b)** $$A = \\frac{1}{2}r^2\\theta = \\frac{1}{2}(36)\\left(\\frac{4}{3}\\right) = \\frac{144}{6} = 24 \\text{ cm}^2$$',
  },
  {
    id: 'trig-40',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'A sector of a circle has radius $r$ cm, angle $\\theta$ radians, area 50 cm² and arc length 10 cm.\n\n(a) Find $r$ and $\\theta$. [3]\n\n(b) Find the perimeter of the sector. [2]',
    markScheme: '(a) $r\\theta = 10$ ... (1) and $\\dfrac{1}{2}r^2\\theta = 50$ ... (2) ✓\nFrom (2): $r^2\\theta = 100$. Divide by (1): $r = 10$ ✓\n$\\theta = 10/10 = 1$ radian ✓\n\n(b) Perimeter $= 2r + s = 20 + 10 = 30$ cm ✓✓',
    workedSolution: '**(a)** Arc length: $r\\theta = 10$ ... (1)\n\nArea: $\\dfrac{1}{2}r^2\\theta = 50 \\implies r^2\\theta = 100$ ... (2)\n\nDivide (2) by (1): $r = \\dfrac{100}{10} = 10$ cm.\n\nFrom (1): $\\theta = \\dfrac{10}{10} = 1$ radian.\n\n**(b)** Perimeter $= 2r + s = 20 + 10 = 30$ cm.',
  },
  {
    id: 'trig-41',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 7,
    body: 'A chord $AB$ of a circle centre $O$ with radius 12 cm subtends an angle of $\\dfrac{\\pi}{3}$ radians at the centre.\n\n(a) Find the area of the minor segment cut off by $AB$. [4]\n\n(b) Find the perimeter of this minor segment. [3]',
    markScheme: '(a) Area of sector $= \\dfrac{1}{2}(144)(\\pi/3) = 24\\pi$ ✓\nArea of triangle $= \\dfrac{1}{2}(12)(12)\\sin(\\pi/3) = 72 \\times \\sqrt{3}/2 = 36\\sqrt{3}$ ✓✓\nSegment area $= 24\\pi - 36\\sqrt{3}$ ✓\n\n(b) Arc length $= 12 \\times \\pi/3 = 4\\pi$ ✓\nChord: triangle $OAB$ is equilateral (two radii, angle $60°$), so $AB = 12$ ✓\nPerimeter $= 4\\pi + 12$ ✓',
    workedSolution: '**(a)** Sector area $= \\dfrac{1}{2}r^2\\theta = \\dfrac{1}{2}(144)\\left(\\dfrac{\\pi}{3}\\right) = 24\\pi$\n\nTriangle area $= \\dfrac{1}{2}(12)(12)\\sin\\dfrac{\\pi}{3} = 72 \\times \\dfrac{\\sqrt{3}}{2} = 36\\sqrt{3}$\n\nSegment area $= 24\\pi - 36\\sqrt{3}$ cm$^2$.\n\n**(b)** Arc length $= r\\theta = 12 \\times \\dfrac{\\pi}{3} = 4\\pi$\n\nTriangle $OAB$ has two sides of 12 cm with included angle $60°$, so it is equilateral. Hence $AB = 12$ cm.\n\nPerimeter $= 4\\pi + 12$ cm.',
  },
  {
    id: 'trig-42',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 9,
    body: 'The diagram shows a circle centre $O$ with radius 10 cm. Points $A$ and $B$ lie on the circle such that angle $AOB = 2.4$ radians. The tangents to the circle at $A$ and $B$ meet at the point $T$.\n\n(a) Find the area of sector $AOB$. [2]\n\n(b) Show that $AT = 10\\tan 1.2$ and find the length $AT$, correct to 3 significant figures. [3]\n\n(c) Find the area enclosed between the two tangents and the minor arc $AB$. [4]',
    markScheme: '(a) $A = \\dfrac{1}{2}(100)(2.4) = 120$ cm² ✓✓\n\n(b) $OA \\perp AT$, angle $AOT = 1.2$ rad (by symmetry) ✓\n$\\tan 1.2 = AT/10$ → $AT = 10\\tan 1.2 = 25.7$ cm ✓✓\n\n(c) Area of triangle $OAT = \\dfrac{1}{2}(10)(10\\tan 1.2) = 50\\tan 1.2$ ✓\nArea of kite $OATB = 2 \\times 50\\tan 1.2 = 100\\tan 1.2$ ✓\nEnclosed area $= 100\\tan 1.2 - 120$ ✓\n$= 100(2.572) - 120 = 257.2 - 120 = 137$ cm² ✓',
    workedSolution: '**(a)** $$\\text{Sector area} = \\frac{1}{2}r^2\\theta = \\frac{1}{2}(100)(2.4) = 120 \\text{ cm}^2$$\n\n**(b)** Since $OA \\perp AT$ (radius to tangent), and by symmetry $\\angle AOT = \\dfrac{2.4}{2} = 1.2$ rad.\n\nIn right triangle $OAT$:\n$$\\tan 1.2 = \\frac{AT}{OA} = \\frac{AT}{10} \\implies AT = 10\\tan 1.2 = 25.7 \\text{ cm}$$\n\n**(c)** Area of triangle $OAT = \\dfrac{1}{2} \\times 10 \\times 10\\tan 1.2 = 50\\tan 1.2$\n\nBy symmetry, area of quadrilateral $OATB = 2 \\times 50\\tan 1.2 = 100\\tan 1.2$.\n\nArea between tangents and arc $= 100\\tan 1.2 - \\text{sector area} = 100\\tan 1.2 - 120$\n\n$= 100(2.572) - 120 = 257.2 - 120 = 137$ cm$^2$.',
  },

  // ── More trig: mixed subtopics ──
  {
    id: 'trig-43',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: '(a) Show that the equation $\\tan^2\\theta - 2\\tan\\theta - 3 = 0$ can be factorised as $(\\tan\\theta - 3)(\\tan\\theta + 1) = 0$. [1]\n\n(b) Hence solve $\\tan^2\\theta - 2\\tan\\theta - 3 = 0$ for $0° \\le \\theta \\le 360°$, giving answers to 1 decimal place. [5]',
    markScheme: '(a) $(\\tan\\theta - 3)(\\tan\\theta + 1) = \\tan^2\\theta - 3\\tan\\theta + \\tan\\theta - 3 = \\tan^2\\theta - 2\\tan\\theta - 3$ ✓\n\n(b) $\\tan\\theta = 3$: $\\theta = 71.6°, 251.6°$ ✓✓\n$\\tan\\theta = -1$: $\\theta = 135°, 315°$ ✓✓✓',
    workedSolution: '**(a)** $(\\tan\\theta - 3)(\\tan\\theta + 1) = \\tan^2\\theta + \\tan\\theta - 3\\tan\\theta - 3 = \\tan^2\\theta - 2\\tan\\theta - 3$ \\checkmark\n\n**(b)** $\\tan\\theta = 3$: $\\theta = \\tan^{-1}(3) = 71.6°$, and $\\theta = 71.6° + 180° = 251.6°$.\n\n$\\tan\\theta = -1$: $\\theta = 180° - 45° = 135°$, and $\\theta = 360° - 45° = 315°$.\n\nSolutions: $\\theta = 71.6°, 135°, 251.6°, 315°$.',
  },
  {
    id: 'trig-44',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'exam-hard',
    type: 'applied',
    marks: 8,
    body: 'A surveyor stands at point $A$ and measures the angle of elevation of the top $T$ of a tower to be $25°$. She walks 40 m directly towards the tower to point $B$, where the angle of elevation is $50°$.\n\n(a) Show that $AT = \\dfrac{40\\sin 50°}{\\sin 25°}$. [4]\n\n(b) Hence find the height of the tower, correct to the nearest metre. [4]',
    markScheme: '(a) In triangle $ABT$: angle $ATB = 50° - 25° = 25°$, angle $ABT = 180° - 50° = 130°$ ✓✓\nSine rule: $\\dfrac{AT}{\\sin 130°} = \\dfrac{40}{\\sin 25°}$ ✓\n$AT = \\dfrac{40\\sin 130°}{\\sin 25°} = \\dfrac{40\\sin 50°}{\\sin 25°}$ ✓ (since $\\sin 130° = \\sin 50°$)\n\n(b) In right triangle with $T$ above ground: $h = AT\\sin 25°$ ✓\n$AT = \\dfrac{40\\sin 50°}{\\sin 25°} = \\dfrac{40(0.766)}{0.4226} = 72.5$ m ✓\n$h = 72.5 \\times \\sin 25° = 72.5 \\times 0.4226 = 30.6$ ✓\nHeight $= 31$ m ✓',
    workedSolution: '**(a)** In triangle $ABT$:\n- $\\angle TAB = 25°$ (given)\n- $\\angle ABT = 180° - 50° = 130°$ (supplementary to angle of elevation at $B$)\n- $\\angle ATB = 180° - 25° - 130° = 25°$\n\nBy the sine rule:\n$$\\frac{AT}{\\sin 130°} = \\frac{40}{\\sin 25°}$$\n\nSince $\\sin 130° = \\sin 50°$:\n$$AT = \\frac{40\\sin 50°}{\\sin 25°}$$\n\n**(b)** The height $h = AT\\sin 25°$:\n$$AT = \\frac{40 \\times 0.766}{0.4226} = 72.5 \\text{ m}$$\n$$h = 72.5 \\times \\sin 25° = 72.5 \\times 0.4226 = 30.6 \\text{ m}$$\n\nHeight $\\approx 31$ m.',
  },
  {
    id: 'trig-45',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'Given that $\\cos\\theta = -\\dfrac{3}{5}$ and $180° < \\theta < 270°$, find the exact value of $\\tan\\theta$.',
    markScheme: '$\\sin^2\\theta = 1 - 9/25 = 16/25$ ✓\n$\\sin\\theta = -4/5$ (negative in Q3) ✓\n$\\tan\\theta = (-4/5)/(-3/5) = 4/3$ ✓',
    workedSolution: '$\\sin^2\\theta = 1 - \\cos^2\\theta = 1 - \\dfrac{9}{25} = \\dfrac{16}{25}$\n\nIn the third quadrant ($180° < \\theta < 270°$), $\\sin\\theta < 0$, so $\\sin\\theta = -\\dfrac{4}{5}$.\n\n$$\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta} = \\frac{-4/5}{-3/5} = \\frac{4}{3}$$',
  },
  {
    id: 'trig-46',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 8,
    body: '(a) By writing $\\sin 2\\theta = 2\\sin\\theta\\cos\\theta$, or otherwise, solve $\\sin 2\\theta = \\cos\\theta$ for $0° \\le \\theta \\le 360°$. [5]\n\n(b) Find the number of solutions of $\\sin 2\\theta = \\cos\\theta$ for $0° \\le \\theta \\le 720°$. [3]',
    markScheme: '(a) $2\\sin\\theta\\cos\\theta = \\cos\\theta$ ✓\n$2\\sin\\theta\\cos\\theta - \\cos\\theta = 0$ → $\\cos\\theta(2\\sin\\theta - 1) = 0$ ✓\n$\\cos\\theta = 0$: $\\theta = 90°, 270°$ ✓\n$\\sin\\theta = 1/2$: $\\theta = 30°, 150°$ ✓✓\n\n(b) In $0°$-$360°$ there are 4 solutions ✓\nIn $360°$-$720°$ the same pattern repeats: 4 more ✓\nTotal: 8 solutions ✓',
    workedSolution: '**(a)** $2\\sin\\theta\\cos\\theta = \\cos\\theta$\n\n$\\cos\\theta(2\\sin\\theta - 1) = 0$\n\n$\\cos\\theta = 0$: $\\theta = 90°, 270°$\n\n$\\sin\\theta = \\dfrac{1}{2}$: $\\theta = 30°, 150°$\n\nSolutions: $\\theta = 30°, 90°, 150°, 270°$.\n\n**(b)** The functions $\\sin 2\\theta$ and $\\cos\\theta$ both have period $360°$, so the pattern repeats. In $0°$ to $360°$ there are 4 solutions, so in $0°$ to $720°$ there are $4 \\times 2 = 8$ solutions.',
  },
  {
    id: 'trig-47',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'hard',
    type: 'applied',
    marks: 6,
    body: 'A piece of wire of length 30 cm is bent to form a sector of a circle with radius $r$ cm.\n\n(a) Show that the area of the sector is $A = 15r - r^2$. [3]\n\n(b) Find the maximum possible area of the sector. [3]',
    markScheme: '(a) Perimeter: $2r + r\\theta = 30$ → $\\theta = (30-2r)/r$ ✓\n$A = \\dfrac{1}{2}r^2\\theta = \\dfrac{1}{2}r^2 \\cdot \\dfrac{30-2r}{r} = \\dfrac{r(30-2r)}{2} = 15r - r^2$ ✓✓\n\n(b) $\\dfrac{dA}{dr} = 15 - 2r = 0$ → $r = 7.5$ ✓\n$\\dfrac{d^2A}{dr^2} = -2 < 0$ → max ✓\n$A = 15(7.5) - (7.5)^2 = 112.5 - 56.25 = 56.25$ cm² ✓',
    workedSolution: '**(a)** Perimeter of sector $= 2r + r\\theta = 30$, so $\\theta = \\dfrac{30 - 2r}{r}$.\n\n$$A = \\frac{1}{2}r^2\\theta = \\frac{1}{2}r^2 \\cdot \\frac{30-2r}{r} = \\frac{r(30-2r)}{2} = 15r - r^2$$\n\n**(b)** $$\\frac{dA}{dr} = 15 - 2r = 0 \\implies r = 7.5$$\n\n$\\dfrac{d^2A}{dr^2} = -2 < 0$ — confirmed maximum.\n\n$$A = 15(7.5) - (7.5)^2 = 112.5 - 56.25 = 56.25 \\text{ cm}^2$$',
  },
  {
    id: 'trig-48',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'exam-hard',
    type: 'proof',
    marks: 6,
    body: 'Prove that $\\dfrac{\\sin^3\\theta + \\cos^3\\theta}{\\sin\\theta + \\cos\\theta} = 1 - \\sin\\theta\\cos\\theta$.',
    markScheme: 'Use sum of cubes: $a^3 + b^3 = (a+b)(a^2 - ab + b^2)$ ✓\nNumerator $= (\\sin\\theta + \\cos\\theta)(\\sin^2\\theta - \\sin\\theta\\cos\\theta + \\cos^2\\theta)$ ✓✓\nCancel $(\\sin\\theta + \\cos\\theta)$: $= \\sin^2\\theta - \\sin\\theta\\cos\\theta + \\cos^2\\theta$ ✓\n$= 1 - \\sin\\theta\\cos\\theta$ ✓✓',
    workedSolution: 'Using the algebraic identity $a^3 + b^3 = (a+b)(a^2 - ab + b^2)$:\n\n$$\\sin^3\\theta + \\cos^3\\theta = (\\sin\\theta + \\cos\\theta)(\\sin^2\\theta - \\sin\\theta\\cos\\theta + \\cos^2\\theta)$$\n\nDivide by $(\\sin\\theta + \\cos\\theta)$:\n\n$$\\frac{\\sin^3\\theta + \\cos^3\\theta}{\\sin\\theta + \\cos\\theta} = \\sin^2\\theta - \\sin\\theta\\cos\\theta + \\cos^2\\theta$$\n\nUsing $\\sin^2\\theta + \\cos^2\\theta = 1$:\n\n$$= 1 - \\sin\\theta\\cos\\theta$$',
  },
  {
    id: 'trig-49',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'intermediate',
    type: 'multi-part',
    marks: 5,
    body: 'In triangle $ABC$, $AB = 9$ cm, $AC = 6$ cm and angle $BAC = 120°$.\n\n(a) Find the exact area of triangle $ABC$. [2]\n\n(b) Find the exact length of $BC$. [3]',
    markScheme: '(a) Area $= \\dfrac{1}{2}(9)(6)\\sin 120° = 27 \\times \\sqrt{3}/2 = \\dfrac{27\\sqrt{3}}{2}$ ✓✓\n\n(b) $BC^2 = 81 + 36 - 2(9)(6)\\cos 120° = 117 - 108(-1/2) = 117 + 54 = 171$ ✓✓\n$BC = \\sqrt{171} = 3\\sqrt{19}$ ✓',
    workedSolution: '**(a)** $$\\text{Area} = \\frac{1}{2}(9)(6)\\sin 120° = 27 \\times \\frac{\\sqrt{3}}{2} = \\frac{27\\sqrt{3}}{2} \\text{ cm}^2$$\n\n**(b)** Using the cosine rule:\n$$BC^2 = 9^2 + 6^2 - 2(9)(6)\\cos 120° = 81 + 36 - 108\\left(-\\frac{1}{2}\\right) = 117 + 54 = 171$$\n$$BC = \\sqrt{171} = \\sqrt{9 \\times 19} = 3\\sqrt{19} \\text{ cm}$$',
  },
  {
    id: 'trig-50',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'hard',
    type: 'short-answer',
    marks: 5,
    body: 'Solve $6\\sin^2\\theta - \\sin\\theta - 1 = 0$ for $0° \\le \\theta \\le 360°$, giving answers to 1 decimal place where appropriate.',
    markScheme: '$(3\\sin\\theta + 1)(2\\sin\\theta - 1) = 0$ ✓\n$\\sin\\theta = -1/3$: $\\theta = 180° + 19.5° = 199.5°$ and $360° - 19.5° = 340.5°$ ✓✓\n$\\sin\\theta = 1/2$: $\\theta = 30°$ and $150°$ ✓✓',
    workedSolution: 'Factorise: $(3\\sin\\theta + 1)(2\\sin\\theta - 1) = 0$\n\n$\\sin\\theta = -\\dfrac{1}{3}$: reference angle $= \\sin^{-1}(1/3) = 19.5°$\nIn Q3 and Q4: $\\theta = 199.5°$ or $\\theta = 340.5°$\n\n$\\sin\\theta = \\dfrac{1}{2}$: $\\theta = 30°$ or $\\theta = 150°$\n\nSolutions: $\\theta = 30°, 150°, 199.5°, 340.5°$.',
  },
  {
    id: 'trig-51',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Solve $\\sin\\theta = -\\dfrac{1}{\\sqrt{2}}$ for $0 \\le \\theta \\le 2\\pi$, giving your answers in terms of $\\pi$.',
    markScheme: 'Reference angle $= \\pi/4$ ✓\nSine is negative in Q3 and Q4 ✓\n$\\theta = \\pi + \\pi/4 = 5\\pi/4$ ✓\n$\\theta = 2\\pi - \\pi/4 = 7\\pi/4$ ✓',
    workedSolution: 'The reference angle is $\\sin^{-1}\\left(\\dfrac{1}{\\sqrt{2}}\\right) = \\dfrac{\\pi}{4}$.\n\nSince $\\sin\\theta$ is negative, $\\theta$ is in Q3 or Q4:\n$$\\theta = \\pi + \\frac{\\pi}{4} = \\frac{5\\pi}{4} \\quad \\text{or} \\quad \\theta = 2\\pi - \\frac{\\pi}{4} = \\frac{7\\pi}{4}$$',
  },
  {
    id: 'trig-52',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 8,
    body: 'A circular pond of radius 5 m has a straight path forming a chord $AB$ of the circle, where the angle $AOB = 1.8$ radians and $O$ is the centre of the pond.\n\n(a) Find the length of the path $AB$. [3]\n\n(b) Find the area of the smaller region of the pond on one side of the path. [3]\n\n(c) A fence is to be placed along the major arc $AB$ and the chord $AB$. Find the total length of fencing needed. [2]',
    markScheme: '(a) Using cosine rule or $AB = 2r\\sin(\\theta/2)$:\n$AB = 2(5)\\sin(0.9) = 10\\sin 0.9 = 10(0.7833) = 7.83$ m ✓✓✓\n\n(b) Segment area $= \\dfrac{1}{2}r^2(\\theta - \\sin\\theta) = \\dfrac{1}{2}(25)(1.8 - \\sin 1.8)$ ✓\n$= 12.5(1.8 - 0.9738) = 12.5(0.8262) = 10.3$ m² ✓✓\n\n(c) Major arc $= r(2\\pi - \\theta) = 5(2\\pi - 1.8) = 10\\pi - 9 = 22.4$ m ✓\nTotal $= 22.4 + 7.83 = 30.3$ m ✓',
    workedSolution: '**(a)** Using $AB = 2r\\sin\\left(\\dfrac{\\theta}{2}\\right)$:\n$$AB = 2(5)\\sin(0.9) = 10(0.7833) = 7.83 \\text{ m}$$\n\n**(b)** Segment area $= \\dfrac{1}{2}r^2(\\theta - \\sin\\theta)$:\n$$= \\frac{1}{2}(25)(1.8 - \\sin 1.8) = 12.5(1.8 - 0.974) = 12.5(0.826) = 10.3 \\text{ m}^2$$\n\n**(c)** Major arc length $= r(2\\pi - \\theta) = 5(2\\pi - 1.8) = 10\\pi - 9 = 22.4$ m.\n\nTotal fencing $= 22.4 + 7.83 = 30.3$ m.',
  },
  {
    id: 'trig-53',
    topic: 'trigonometry',
    subtopic: 'Trigonometric ratios',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 5,
    body: 'Given that $\\sin\\theta = \\dfrac{p}{q}$ where $\\theta$ is acute and $p, q > 0$,\n\n(a) express $\\cos\\theta$ in terms of $p$ and $q$, [2]\n\n(b) express $\\tan\\theta$ in terms of $p$ and $q$, [1]\n\n(c) show that $\\dfrac{1 + \\tan^2\\theta}{1 - \\tan^2\\theta} = \\dfrac{q^2}{q^2 - 2p^2}$. [2]',
    markScheme: '(a) $\\cos\\theta = \\sqrt{1 - p^2/q^2} = \\dfrac{\\sqrt{q^2 - p^2}}{q}$ ✓✓\n\n(b) $\\tan\\theta = \\dfrac{p}{\\sqrt{q^2-p^2}}$ ✓\n\n(c) $\\tan^2\\theta = \\dfrac{p^2}{q^2-p^2}$ ✓\n$\\dfrac{1 + p^2/(q^2-p^2)}{1 - p^2/(q^2-p^2)} = \\dfrac{q^2/(q^2-p^2)}{(q^2-2p^2)/(q^2-p^2)} = \\dfrac{q^2}{q^2-2p^2}$ ✓',
    workedSolution: '**(a)** $\\cos\\theta = \\sqrt{1 - \\sin^2\\theta} = \\sqrt{1 - \\frac{p^2}{q^2}} = \\frac{\\sqrt{q^2 - p^2}}{q}$\n\n**(b)** $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta} = \\frac{p/q}{\\sqrt{q^2-p^2}/q} = \\frac{p}{\\sqrt{q^2-p^2}}$\n\n**(c)** $\\tan^2\\theta = \\frac{p^2}{q^2-p^2}$\n\n$$\\frac{1+\\tan^2\\theta}{1-\\tan^2\\theta} = \\frac{1 + \\frac{p^2}{q^2-p^2}}{1 - \\frac{p^2}{q^2-p^2}} = \\frac{\\frac{q^2-p^2+p^2}{q^2-p^2}}{\\frac{q^2-p^2-p^2}{q^2-p^2}} = \\frac{q^2}{q^2-2p^2}$$',
  },
  {
    id: 'trig-54',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 9,
    body: 'In the quadrilateral $ABCD$, $AB = 5$ cm, $BC = 7$ cm, $CD = 8$ cm, angle $ABC = 100°$ and angle $ACD = 35°$.\n\n(a) Find the length $AC$, correct to 3 significant figures. [3]\n\n(b) Find the angle $ACD$... Given that angle $ADC = 75°$, find the length $AD$. [3]\n\n(c) Find the area of the quadrilateral $ABCD$. [3]',
    markScheme: '(a) Cosine rule in $\\triangle ABC$:\n$AC^2 = 25 + 49 - 2(5)(7)\\cos 100° = 74 - 70(-0.1736) = 74 + 12.15 = 86.15$ ✓✓\n$AC = 9.28$ cm ✓\n\n(b) In $\\triangle ACD$: angle $ACD = 35°$, angle $ADC = 75°$, so angle $DAC = 70°$ ✓\nSine rule: $\\dfrac{AD}{\\sin 35°} = \\dfrac{9.28}{\\sin 75°}$ ✓\n$AD = \\dfrac{9.28 \\sin 35°}{\\sin 75°} = \\dfrac{9.28(0.5736)}{0.9659} = 5.51$ cm ✓\n\n(c) Area $\\triangle ABC = \\dfrac{1}{2}(5)(7)\\sin 100° = 17.5(0.9848) = 17.2$ cm² ✓\nArea $\\triangle ACD = \\dfrac{1}{2}(9.28)(8)\\sin 35° = 37.12(0.5736) = 21.3$ cm² ✓\nTotal $= 38.5$ cm² ✓',
    workedSolution: '**(a)** In $\\triangle ABC$ using the cosine rule:\n$$AC^2 = 5^2 + 7^2 - 2(5)(7)\\cos 100° = 74 + 12.15 = 86.15$$\n$$AC = 9.28 \\text{ cm}$$\n\n**(b)** In $\\triangle ACD$: $\\angle ACD = 35°$, $\\angle ADC = 75°$, so $\\angle DAC = 180° - 35° - 75° = 70°$.\n\nBy the sine rule:\n$$\\frac{AD}{\\sin 35°} = \\frac{AC}{\\sin 75°} \\implies AD = \\frac{9.28\\sin 35°}{\\sin 75°} = 5.51 \\text{ cm}$$\n\n**(c)** Area of $\\triangle ABC = \\dfrac{1}{2}(5)(7)\\sin 100° = 17.2$ cm$^2$\n\nArea of $\\triangle ACD = \\dfrac{1}{2}(AC)(CD)\\sin 35° = \\dfrac{1}{2}(9.28)(8)(0.574) = 21.3$ cm$^2$\n\nTotal area $= 17.2 + 21.3 = 38.5$ cm$^2$.',
  },
  {
    id: 'trig-55',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 4,
    body: 'Solve $\\cos 2\\theta = 0.5$ for $0° \\le \\theta \\le 360°$.',
    markScheme: 'Let $\\alpha = 2\\theta$, $0° \\le \\alpha \\le 720°$ ✓\n$\\alpha = 60°, 300°, 420°, 660°$ ✓✓\n$\\theta = 30°, 150°, 210°, 330°$ ✓',
    workedSolution: 'Let $\\alpha = 2\\theta$, so $0° \\le \\alpha \\le 720°$ and $\\cos\\alpha = 0.5$.\n\n$\\alpha = 60°, 300°$ (first cycle), $420°, 660°$ (second cycle).\n\n$$\\theta = 30°, 150°, 210°, 330°$$',
  },
  {
    id: 'trig-56',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'intermediate',
    type: 'short-answer',
    marks: 3,
    body: 'The area of a sector is $32\\pi$ cm² and the arc length is $8\\pi$ cm. Find the radius and the angle of the sector in radians.',
    markScheme: '$r\\theta = 8\\pi$ and $\\dfrac{1}{2}r^2\\theta = 32\\pi$ ✓\nDivide: $r/2 = 4$ → $r = 8$ cm ✓\n$\\theta = 8\\pi/8 = \\pi$ radians ✓',
    workedSolution: 'From $r\\theta = 8\\pi$ and $\\dfrac{1}{2}r^2\\theta = 32\\pi$:\n\n$$\\frac{\\frac{1}{2}r^2\\theta}{r\\theta} = \\frac{32\\pi}{8\\pi} \\implies \\frac{r}{2} = 4 \\implies r = 8 \\text{ cm}$$\n\n$$\\theta = \\frac{8\\pi}{8} = \\pi \\text{ radians}$$',
  },
  {
    id: 'trig-57',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Simplify $\\sin^2 40° + \\cos^2 40°$.',
    markScheme: 'Using $\\sin^2\\theta + \\cos^2\\theta = 1$ ✓\nAnswer: $1$ ✓',
    workedSolution: 'By the Pythagorean identity:\n$$\\sin^2 40° + \\cos^2 40° = 1$$',
  },
  {
    id: 'trig-58',
    topic: 'trigonometry',
    subtopic: 'Radians',
    difficulty: 'foundation',
    type: 'short-answer',
    marks: 2,
    body: 'Convert $45°$ to radians, giving your answer in terms of $\\pi$.',
    markScheme: '$45° \\times \\dfrac{\\pi}{180°} = \\dfrac{\\pi}{4}$ ✓✓',
    workedSolution: '$$45° = 45 \\times \\frac{\\pi}{180} = \\frac{\\pi}{4} \\text{ radians}$$',
  },
  {
    id: 'trig-59',
    topic: 'trigonometry',
    subtopic: 'Solving trig equations',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 7,
    body: '(a) Show that the equation $4\\cos^2\\theta + 5\\sin\\theta = 5$ can be written as $4\\sin^2\\theta - 5\\sin\\theta + 1 = 0$. [2]\n\n(b) Hence solve $4\\cos^2\\theta + 5\\sin\\theta = 5$ for $0 \\le \\theta \\le 2\\pi$, giving your answers in terms of $\\pi$. [5]',
    markScheme: '(a) $4(1 - \\sin^2\\theta) + 5\\sin\\theta = 5$ ✓\n$4 - 4\\sin^2\\theta + 5\\sin\\theta - 5 = 0$ → $4\\sin^2\\theta - 5\\sin\\theta + 1 = 0$ ✓\n\n(b) $(4\\sin\\theta - 1)(\\sin\\theta - 1) = 0$ ✓\n$\\sin\\theta = 1$: $\\theta = \\pi/2$ ✓\n$\\sin\\theta = 1/4$: $\\theta = \\sin^{-1}(0.25) = 0.253$ rad and $\\pi - 0.253 = 2.889$ rad ✓✓✓',
    workedSolution: '**(a)** Replace $\\cos^2\\theta = 1 - \\sin^2\\theta$:\n$$4(1 - \\sin^2\\theta) + 5\\sin\\theta = 5$$\n$$4 - 4\\sin^2\\theta + 5\\sin\\theta = 5$$\n$$4\\sin^2\\theta - 5\\sin\\theta + 1 = 0$$\n\n**(b)** Factorise: $(4\\sin\\theta - 1)(\\sin\\theta - 1) = 0$\n\n$\\sin\\theta = 1$: $\\theta = \\dfrac{\\pi}{2}$\n\n$\\sin\\theta = \\dfrac{1}{4}$: $\\theta = \\sin^{-1}(0.25) \\approx 0.253$ and $\\theta = \\pi - 0.253 \\approx 2.889$.\n\nSolutions: $\\theta = 0.253, \\dfrac{\\pi}{2}, 2.889$ (to 3 d.p.).',
  },
  {
    id: 'trig-60',
    topic: 'trigonometry',
    subtopic: 'Sine and cosine rules',
    difficulty: 'hard',
    type: 'multi-part',
    marks: 6,
    body: 'In triangle $ABC$, $a = 10$ cm, $b = 7$ cm and $C = 50°$.\n\n(a) Find the area of triangle $ABC$. [2]\n\n(b) Find the length of side $c$. [2]\n\n(c) Find angle $A$, giving your answer to 1 decimal place. [2]',
    markScheme: '(a) Area $= \\dfrac{1}{2}(10)(7)\\sin 50° = 35(0.766) = 26.8$ cm² ✓✓\n\n(b) $c^2 = 100 + 49 - 2(10)(7)\\cos 50° = 149 - 140(0.6428) = 149 - 90.0 = 59.0$ ✓\n$c = 7.68$ cm ✓\n\n(c) Sine rule: $\\dfrac{\\sin A}{10} = \\dfrac{\\sin 50°}{7.68}$ ✓\n$\\sin A = \\dfrac{10 \\sin 50°}{7.68} = 0.9975$ → $A = 85.9°$ ✓',
    workedSolution: '**(a)** $$\\text{Area} = \\frac{1}{2}ab\\sin C = \\frac{1}{2}(10)(7)\\sin 50° = 35(0.766) = 26.8 \\text{ cm}^2$$\n\n**(b)** Using the cosine rule:\n$$c^2 = a^2 + b^2 - 2ab\\cos C = 100 + 49 - 140\\cos 50° = 149 - 90.0 = 59.0$$\n$$c = 7.68 \\text{ cm}$$\n\n**(c)** Using the sine rule:\n$$\\frac{\\sin A}{a} = \\frac{\\sin C}{c} \\implies \\sin A = \\frac{10\\sin 50°}{7.68} = 0.9975$$\n$$A = 85.9°$$',
  },
  {
    id: 'trig-61',
    topic: 'trigonometry',
    subtopic: 'Trigonometric identities',
    difficulty: 'exam-hard',
    type: 'proof',
    marks: 6,
    body: 'Prove that $\\dfrac{\\tan\\theta + 1}{\\tan\\theta - 1} = \\dfrac{\\sin\\theta + \\cos\\theta}{\\sin\\theta - \\cos\\theta}$.',
    markScheme: 'LHS: $\\dfrac{\\tan\\theta + 1}{\\tan\\theta - 1} = \\dfrac{\\sin\\theta/\\cos\\theta + 1}{\\sin\\theta/\\cos\\theta - 1}$ ✓✓\n$= \\dfrac{(\\sin\\theta + \\cos\\theta)/\\cos\\theta}{(\\sin\\theta - \\cos\\theta)/\\cos\\theta}$ ✓✓\n$= \\dfrac{\\sin\\theta + \\cos\\theta}{\\sin\\theta - \\cos\\theta}$ ✓✓',
    workedSolution: '$$\\text{LHS} = \\frac{\\tan\\theta + 1}{\\tan\\theta - 1} = \\frac{\\frac{\\sin\\theta}{\\cos\\theta} + 1}{\\frac{\\sin\\theta}{\\cos\\theta} - 1}$$\n\nMultiply numerator and denominator by $\\cos\\theta$:\n\n$$= \\frac{\\sin\\theta + \\cos\\theta}{\\sin\\theta - \\cos\\theta} = \\text{RHS}$$',
  },
  {
    id: 'trig-62',
    topic: 'trigonometry',
    subtopic: 'Arc length and sector area',
    difficulty: 'exam-hard',
    type: 'multi-part',
    marks: 10,
    body: 'The figure shows two circles, each of radius 6 cm, whose centres $A$ and $B$ are 8 cm apart. The circles intersect at points $P$ and $Q$.\n\n(a) Show that $\\cos(\\angle PAB) = \\dfrac{2}{3}$. [2]\n\n(b) Find $\\angle PAB$ in radians, correct to 4 significant figures. [1]\n\n(c) Find the area of the region common to both circles (the "vesica"). [7]',
    markScheme: '(a) In triangle $APB$: $AP = 6$, $AB = 8$, $BP = 6$. Wait — that gives $AB = 8$, $AP = BP = 6$.\nCosine rule: $BP^2 = AP^2 + AB^2 - 2(AP)(AB)\\cos(\\angle PAB)$\n$36 = 36 + 64 - 2(6)(8)\\cos(\\angle PAB)$ → $36 = 100 - 96\\cos(\\angle PAB)$ ✓\n$\\cos(\\angle PAB) = 64/96 = 2/3$ ✓\n\n(b) $\\angle PAB = \\cos^{-1}(2/3) = 0.8411$ rad ✓\n\n(c) $\\angle PAQ = 2 \\times 0.8411 = 1.6822$ rad ✓\nBy symmetry, $\\angle PBQ = 2 \\times \\cos^{-1}(2/3) = 1.6822$ rad ✓\nArea of one segment (from circle $A$) $= \\frac{1}{2}r^2(\\theta - \\sin\\theta) = \\frac{1}{2}(36)(1.6822 - \\sin 1.6822)$ ✓\n$\\sin 1.6822 = 0.9926$ ✓\n$= 18(1.6822 - 0.9926) = 18(0.6896) = 12.41$ ✓\nTotal overlap $= 2 \\times 12.41 = 24.8$ cm² ✓✓',
    workedSolution: '**(a)** In $\\triangle APB$: $AP = 6$, $AB = 8$, $BP = 6$.\n\nCosine rule:\n$$BP^2 = AP^2 + AB^2 - 2(AP)(AB)\\cos(\\angle PAB)$$\n$$36 = 36 + 64 - 96\\cos(\\angle PAB)$$\n$$96\\cos(\\angle PAB) = 64 \\implies \\cos(\\angle PAB) = \\frac{2}{3}$$\n\n**(b)** $\\angle PAB = \\cos^{-1}(2/3) = 0.8411$ rad.\n\n**(c)** The full angle at $A$ subtended by the overlap is $\\angle PAQ = 2 \\times 0.8411 = 1.6822$ rad.\n\nBy symmetry, $\\angle PBQ = 1.6822$ rad.\n\nThe overlap region consists of two circular segments:\n\nOne segment (from circle $A$):\n$$= \\frac{1}{2}(6)^2(1.6822 - \\sin 1.6822) = 18(1.6822 - 0.9926) = 18(0.6896) = 12.41 \\text{ cm}^2$$\n\nBy symmetry, the segment from circle $B$ has the same area.\n\nTotal overlap area $= 2 \\times 12.41 = 24.8$ cm$^2$.',
  },
];
